<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StagingCollectingMethods', 'doctrine');

/**
 * BaseStagingCollectingMethods
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $staging_ref
 * @property integer $collecting_method_ref
 * @property CollectingMethods $CollectingMethods
 * @property Staging $Staging
 * 
 * @method integer                  getId()                    Returns the current record's "id" value
 * @method integer                  getStagingRef()            Returns the current record's "staging_ref" value
 * @method integer                  getCollectingMethodRef()   Returns the current record's "collecting_method_ref" value
 * @method CollectingMethods        getCollectingMethods()     Returns the current record's "CollectingMethods" value
 * @method Staging                  getStaging()               Returns the current record's "Staging" value
 * @method StagingCollectingMethods setId()                    Sets the current record's "id" value
 * @method StagingCollectingMethods setStagingRef()            Sets the current record's "staging_ref" value
 * @method StagingCollectingMethods setCollectingMethodRef()   Sets the current record's "collecting_method_ref" value
 * @method StagingCollectingMethods setCollectingMethods()     Sets the current record's "CollectingMethods" value
 * @method StagingCollectingMethods setStaging()               Sets the current record's "Staging" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStagingCollectingMethods extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('staging_collecting_methods');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'staging_collecting_methods_id',
             'length' => 4,
             ));
        $this->hasColumn('staging_ref', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('collecting_method_ref', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CollectingMethods', array(
             'local' => 'collecting_method_ref',
             'foreign' => 'id'));

        $this->hasOne('Staging', array(
             'local' => 'staging_ref',
             'foreign' => 'id'));
    }
}