<?php

/**
 * BaseIdentifiersUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Users
 * 
 * @method Doctrine_Collection getUsers() Returns the current record's "Users" collection
 * @method IdentifiersUsers    setUsers() Sets the current record's "Users" collection
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIdentifiersUsers extends Identifiers
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Users', array(
             'local' => 'record_id',
             'foreign' => 'id'));
    }
}