<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GeometryColumns', 'doctrine');

/**
 * BaseGeometryColumns
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * 
 * @method integer         getId() Returns the current record's "id" value
 * @method GeometryColumns setId() Sets the current record's "id" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeometryColumns extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('geometry_columns');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}