<?php

/**
 * BaseGeoreferencesByService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $data_origin
 * @property string $gtu_refs
 * @property integer $count_specimens
 * @property string $wfs_url
 * @property string $wfs_table
 * @property string $wfs_id
 * @property string $root_urls_service
 * @property string $data_urls
 * @property string $service_ids
 * @property string $service_stable_ids
 * @property string $service_responses
 * @property string $response_names
 * @property string $service_categories
 * @property string $service_queries
 * @property string $tag_group_name
 * @property string $tag_sub_group_name
 * @property string $name
 * @property string $country
 * @property string $country_iso
 * @property string $longitude
 * @property string $latitude
 * @property string $geom_type
 * @property string $geom_wkt
 * @property string $query_date
 * @property string $creator
 * @property string $validation_date
 * @property string $validator
 * @property string $validation_level
 * @property string $validation_comment
 * 
 * @method integer                getId()                 Returns the current record's "id" value
 * @method string                 getDataOrigin()         Returns the current record's "data_origin" value
 * @method string                 getGtuRefs()            Returns the current record's "gtu_refs" value
 * @method integer                getCountSpecimens()     Returns the current record's "count_specimens" value
 * @method string                 getWfsUrl()             Returns the current record's "wfs_url" value
 * @method string                 getWfsTable()           Returns the current record's "wfs_table" value
 * @method string                 getWfsId()              Returns the current record's "wfs_id" value
 * @method string                 getRootUrlsService()    Returns the current record's "root_urls_service" value
 * @method string                 getDataUrls()           Returns the current record's "data_urls" value
 * @method string                 getServiceIds()         Returns the current record's "service_ids" value
 * @method string                 getServiceStableIds()   Returns the current record's "service_stable_ids" value
 * @method string                 getServiceResponses()   Returns the current record's "service_responses" value
 * @method string                 getResponseNames()      Returns the current record's "response_names" value
 * @method string                 getServiceCategories()  Returns the current record's "service_categories" value
 * @method string                 getServiceQueries()     Returns the current record's "service_queries" value
 * @method string                 getTagGroupName()       Returns the current record's "tag_group_name" value
 * @method string                 getTagSubGroupName()    Returns the current record's "tag_sub_group_name" value
 * @method string                 getName()               Returns the current record's "name" value
 * @method string                 getCountry()            Returns the current record's "country" value
 * @method string                 getCountryIso()         Returns the current record's "country_iso" value
 * @method string                 getLongitude()          Returns the current record's "longitude" value
 * @method string                 getLatitude()           Returns the current record's "latitude" value
 * @method string                 getGeomType()           Returns the current record's "geom_type" value
 * @method string                 getGeomWkt()            Returns the current record's "geom_wkt" value
 * @method string                 getQueryDate()          Returns the current record's "query_date" value
 * @method string                 getCreator()            Returns the current record's "creator" value
 * @method string                 getValidationDate()     Returns the current record's "validation_date" value
 * @method string                 getValidator()          Returns the current record's "validator" value
 * @method string                 getValidationLevel()    Returns the current record's "validation_level" value
 * @method string                 getValidationComment()  Returns the current record's "validation_comment" value
 * @method GeoreferencesByService setId()                 Sets the current record's "id" value
 * @method GeoreferencesByService setDataOrigin()         Sets the current record's "data_origin" value
 * @method GeoreferencesByService setGtuRefs()            Sets the current record's "gtu_refs" value
 * @method GeoreferencesByService setCountSpecimens()     Sets the current record's "count_specimens" value
 * @method GeoreferencesByService setWfsUrl()             Sets the current record's "wfs_url" value
 * @method GeoreferencesByService setWfsTable()           Sets the current record's "wfs_table" value
 * @method GeoreferencesByService setWfsId()              Sets the current record's "wfs_id" value
 * @method GeoreferencesByService setRootUrlsService()    Sets the current record's "root_urls_service" value
 * @method GeoreferencesByService setDataUrls()           Sets the current record's "data_urls" value
 * @method GeoreferencesByService setServiceIds()         Sets the current record's "service_ids" value
 * @method GeoreferencesByService setServiceStableIds()   Sets the current record's "service_stable_ids" value
 * @method GeoreferencesByService setServiceResponses()   Sets the current record's "service_responses" value
 * @method GeoreferencesByService setResponseNames()      Sets the current record's "response_names" value
 * @method GeoreferencesByService setServiceCategories()  Sets the current record's "service_categories" value
 * @method GeoreferencesByService setServiceQueries()     Sets the current record's "service_queries" value
 * @method GeoreferencesByService setTagGroupName()       Sets the current record's "tag_group_name" value
 * @method GeoreferencesByService setTagSubGroupName()    Sets the current record's "tag_sub_group_name" value
 * @method GeoreferencesByService setName()               Sets the current record's "name" value
 * @method GeoreferencesByService setCountry()            Sets the current record's "country" value
 * @method GeoreferencesByService setCountryIso()         Sets the current record's "country_iso" value
 * @method GeoreferencesByService setLongitude()          Sets the current record's "longitude" value
 * @method GeoreferencesByService setLatitude()           Sets the current record's "latitude" value
 * @method GeoreferencesByService setGeomType()           Sets the current record's "geom_type" value
 * @method GeoreferencesByService setGeomWkt()            Sets the current record's "geom_wkt" value
 * @method GeoreferencesByService setQueryDate()          Sets the current record's "query_date" value
 * @method GeoreferencesByService setCreator()            Sets the current record's "creator" value
 * @method GeoreferencesByService setValidationDate()     Sets the current record's "validation_date" value
 * @method GeoreferencesByService setValidator()          Sets the current record's "validator" value
 * @method GeoreferencesByService setValidationLevel()    Sets the current record's "validation_level" value
 * @method GeoreferencesByService setValidationComment()  Sets the current record's "validation_comment" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeoreferencesByService extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('georeferences_by_service');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('data_origin', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_refs', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('count_specimens', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('wfs_url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('wfs_table', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('wfs_id', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('root_urls_service', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('data_urls', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('service_ids', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('service_stable_ids', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('service_responses', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('response_names', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('service_categories', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('service_queries', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tag_group_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tag_sub_group_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('country', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('country_iso', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('longitude', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('latitude', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('geom_type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('geom_wkt', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('query_date', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('creator', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('validation_date', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('validator', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('validation_level', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('validation_comment', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}