<?php

/**
 * BaseStagingUpdateSpecimenRelationship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $relationship_type
 * @property integer $specimen_submitted_ref
 * @property string $specimen_uuid
 * @property string $specimen_main_code
 * @property integer $specimen_ref
 * @property integer $specimen_related_submitted_ref
 * @property string $specimen_related_uuid
 * @property string $specimen_related_main_code
 * @property integer $specimen_related_ref
 * @property integer $import_ref
 * @property string $status
 * @property boolean $to_import
 * @property boolean $imported
 * @property Imports $Import
 * @property Specimens $Specimen1
 * @property Specimens $Specimen2
 * 
 * @method integer                           getId()                             Returns the current record's "id" value
 * @method string                            getRelationshipType()               Returns the current record's "relationship_type" value
 * @method integer                           getSpecimenSubmittedRef()           Returns the current record's "specimen_submitted_ref" value
 * @method string                            getSpecimenUuid()                   Returns the current record's "specimen_uuid" value
 * @method string                            getSpecimenMainCode()               Returns the current record's "specimen_main_code" value
 * @method integer                           getSpecimenRef()                    Returns the current record's "specimen_ref" value
 * @method integer                           getSpecimenRelatedSubmittedRef()    Returns the current record's "specimen_related_submitted_ref" value
 * @method string                            getSpecimenRelatedUuid()            Returns the current record's "specimen_related_uuid" value
 * @method string                            getSpecimenRelatedMainCode()        Returns the current record's "specimen_related_main_code" value
 * @method integer                           getSpecimenRelatedRef()             Returns the current record's "specimen_related_ref" value
 * @method integer                           getImportRef()                      Returns the current record's "import_ref" value
 * @method string                            getStatus()                         Returns the current record's "status" value
 * @method boolean                           getToImport()                       Returns the current record's "to_import" value
 * @method boolean                           getImported()                       Returns the current record's "imported" value
 * @method Imports                           getImport()                         Returns the current record's "Import" value
 * @method Specimens                         getSpecimen1()                      Returns the current record's "Specimen1" value
 * @method Specimens                         getSpecimen2()                      Returns the current record's "Specimen2" value
 * @method StagingUpdateSpecimenRelationship setId()                             Sets the current record's "id" value
 * @method StagingUpdateSpecimenRelationship setRelationshipType()               Sets the current record's "relationship_type" value
 * @method StagingUpdateSpecimenRelationship setSpecimenSubmittedRef()           Sets the current record's "specimen_submitted_ref" value
 * @method StagingUpdateSpecimenRelationship setSpecimenUuid()                   Sets the current record's "specimen_uuid" value
 * @method StagingUpdateSpecimenRelationship setSpecimenMainCode()               Sets the current record's "specimen_main_code" value
 * @method StagingUpdateSpecimenRelationship setSpecimenRef()                    Sets the current record's "specimen_ref" value
 * @method StagingUpdateSpecimenRelationship setSpecimenRelatedSubmittedRef()    Sets the current record's "specimen_related_submitted_ref" value
 * @method StagingUpdateSpecimenRelationship setSpecimenRelatedUuid()            Sets the current record's "specimen_related_uuid" value
 * @method StagingUpdateSpecimenRelationship setSpecimenRelatedMainCode()        Sets the current record's "specimen_related_main_code" value
 * @method StagingUpdateSpecimenRelationship setSpecimenRelatedRef()             Sets the current record's "specimen_related_ref" value
 * @method StagingUpdateSpecimenRelationship setImportRef()                      Sets the current record's "import_ref" value
 * @method StagingUpdateSpecimenRelationship setStatus()                         Sets the current record's "status" value
 * @method StagingUpdateSpecimenRelationship setToImport()                       Sets the current record's "to_import" value
 * @method StagingUpdateSpecimenRelationship setImported()                       Sets the current record's "imported" value
 * @method StagingUpdateSpecimenRelationship setImport()                         Sets the current record's "Import" value
 * @method StagingUpdateSpecimenRelationship setSpecimen1()                      Sets the current record's "Specimen1" value
 * @method StagingUpdateSpecimenRelationship setSpecimen2()                      Sets the current record's "Specimen2" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStagingUpdateSpecimenRelationship extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('staging_update_specimen_relationship');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('relationship_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('specimen_submitted_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_uuid', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_main_code', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_related_submitted_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_related_uuid', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_related_main_code', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_related_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('import_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('to_import', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('imported', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Imports as Import', array(
             'local' => 'import_ref',
             'foreign' => 'id'));

        $this->hasOne('Specimens as Specimen1', array(
             'local' => 'specimen_ref',
             'foreign' => 'id'));

        $this->hasOne('Specimens as Specimen2', array(
             'local' => 'specimen_related_ref',
             'foreign' => 'id'));
    }
}