<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TemplateTableRecordRef', 'doctrine');

/**
 * BaseTemplateTableRecordRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $referenced_relation
 * @property integer $record_id
 * 
 * @method integer                getId()                  Returns the current record's "id" value
 * @method string                 getReferencedRelation()  Returns the current record's "referenced_relation" value
 * @method integer                getRecordId()            Returns the current record's "record_id" value
 * @method TemplateTableRecordRef setId()                  Sets the current record's "id" value
 * @method TemplateTableRecordRef setReferencedRelation()  Sets the current record's "referenced_relation" value
 * @method TemplateTableRecordRef setRecordId()            Sets the current record's "record_id" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemplateTableRecordRef extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('template_table_record_ref');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('referenced_relation', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('record_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}