<?php

/**
 * BaseDoctrineGtuComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $record_id
 * @property string $comments
 * @property Gtu $Gtu
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method integer             getRecordId()  Returns the current record's "record_id" value
 * @method string              getComments()  Returns the current record's "comments" value
 * @method Gtu                 getGtu()       Returns the current record's "Gtu" value
 * @method DoctrineGtuComments setId()        Sets the current record's "id" value
 * @method DoctrineGtuComments setRecordId()  Sets the current record's "record_id" value
 * @method DoctrineGtuComments setComments()  Sets the current record's "comments" value
 * @method DoctrineGtuComments setGtu()       Sets the current record's "Gtu" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDoctrineGtuComments extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('doctrine_gtu_comments');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('record_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('comments', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gtu', array(
             'local' => 'record_id',
             'foreign' => 'id'));
    }
}