<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ZzzUsersTrackingArchived', 'doctrine');

/**
 * BaseZzzUsersTrackingArchived
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $referenced_relation
 * @property integer $record_id
 * @property integer $user_ref
 * @property string $action
 * @property hstore $old_value
 * @property hstore $new_value
 * @property timestamp $modification_date_time
 * @property integer $specimen_individual_ref
 * @property integer $specimen_ref
 * 
 * @method integer                  getId()                      Returns the current record's "id" value
 * @method string                   getReferencedRelation()      Returns the current record's "referenced_relation" value
 * @method integer                  getRecordId()                Returns the current record's "record_id" value
 * @method integer                  getUserRef()                 Returns the current record's "user_ref" value
 * @method string                   getAction()                  Returns the current record's "action" value
 * @method hstore                   getOldValue()                Returns the current record's "old_value" value
 * @method hstore                   getNewValue()                Returns the current record's "new_value" value
 * @method timestamp                getModificationDateTime()    Returns the current record's "modification_date_time" value
 * @method integer                  getSpecimenIndividualRef()   Returns the current record's "specimen_individual_ref" value
 * @method integer                  getSpecimenRef()             Returns the current record's "specimen_ref" value
 * @method ZzzUsersTrackingArchived setId()                      Sets the current record's "id" value
 * @method ZzzUsersTrackingArchived setReferencedRelation()      Sets the current record's "referenced_relation" value
 * @method ZzzUsersTrackingArchived setRecordId()                Sets the current record's "record_id" value
 * @method ZzzUsersTrackingArchived setUserRef()                 Sets the current record's "user_ref" value
 * @method ZzzUsersTrackingArchived setAction()                  Sets the current record's "action" value
 * @method ZzzUsersTrackingArchived setOldValue()                Sets the current record's "old_value" value
 * @method ZzzUsersTrackingArchived setNewValue()                Sets the current record's "new_value" value
 * @method ZzzUsersTrackingArchived setModificationDateTime()    Sets the current record's "modification_date_time" value
 * @method ZzzUsersTrackingArchived setSpecimenIndividualRef()   Sets the current record's "specimen_individual_ref" value
 * @method ZzzUsersTrackingArchived setSpecimenRef()             Sets the current record's "specimen_ref" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZzzUsersTrackingArchived extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('zzz_users_tracking_archived');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('referenced_relation', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('record_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_ref', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('action', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('old_value', 'hstore', null, array(
             'type' => 'hstore',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('new_value', 'hstore', null, array(
             'type' => 'hstore',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('modification_date_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('specimen_individual_ref', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('specimen_ref', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}