<?php

/**
 * BaseReportSpecimens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $query_id
 * @property text $creation_date
 * @property integer $id_specimen
 * @property string $collection_code
 * @property string $code
 * @property string $additional_codes
 * @property string $uuid
 * @property string $ig_num
 * @property string $taxon_name
 * @property string $author
 * @property string $full_scientific_name
 * @property string $family
 * @property string $type
 * @property integer $specimen_count_min
 * @property integer $specimen_count_max
 * @property string $identifiers
 * @property string $abbreviated_identifiers
 * @property string $identification_year
 * @property float $longitude
 * @property float $latitude
 * @property string $longitude_varchar
 * @property string $latitude_varchar
 * @property string $gtu_country_tag_value
 * @property string $gtu_province_tag_value
 * @property string $municipality
 * @property string $gtu_others_tag_value
 * @property string $gtu_code
 * @property float $gtu_elevation
 * @property float $collecting_year_from
 * @property float $collecting_month_from
 * @property float $collecting_day_from
 * @property float $collecting_year_to
 * @property float $collecting_month_to
 * @property float $collecting_day_to
 * @property string $properties_locality
 * @property string $collectors
 * @property string $abbreviated_collectors
 * @property string $expedition_name
 * @property string $donators
 * @property string $abbreviated_donators
 * @property string $acquisition_category
 * @property string $acquisition_date
 * @property string $sex
 * @property string $stage
 * @property string $state
 * @property integer $specimen_count_males_min
 * @property integer $specimen_count_males_max
 * @property integer $specimen_count_females_min
 * @property integer $specimen_count_females_max
 * @property integer $specimen_count_juveniles_min
 * @property integer $specimen_count_juveniles_max
 * @property string $social_status
 * @property string $specimen_part
 * @property boolean $complete
 * @property string $object_name
 * @property string $specimen_status
 * @property string $container_storage
 * @property string $method
 * @property string $tool
 * @property string $comment
 * @property string $properties_all
 * @property text $specimen_creation_date
 * @property string $building
 * @property string $floor
 * @property string $room
 * @property string $row
 * @property string $shelf
 * @property string $container
 * @property string $sub_container
 * 
 * @method integer         getId()                           Returns the current record's "id" value
 * @method integer         getQueryId()                      Returns the current record's "query_id" value
 * @method text            getCreationDate()                 Returns the current record's "creation_date" value
 * @method integer         getIdSpecimen()                   Returns the current record's "id_specimen" value
 * @method string          getCollectionCode()               Returns the current record's "collection_code" value
 * @method string          getCode()                         Returns the current record's "code" value
 * @method string          getAdditionalCodes()              Returns the current record's "additional_codes" value
 * @method string          getUuid()                         Returns the current record's "uuid" value
 * @method string          getIgNum()                        Returns the current record's "ig_num" value
 * @method string          getTaxonName()                    Returns the current record's "taxon_name" value
 * @method string          getAuthor()                       Returns the current record's "author" value
 * @method string          getFullScientificName()           Returns the current record's "full_scientific_name" value
 * @method string          getFamily()                       Returns the current record's "family" value
 * @method string          getType()                         Returns the current record's "type" value
 * @method integer         getSpecimenCountMin()             Returns the current record's "specimen_count_min" value
 * @method integer         getSpecimenCountMax()             Returns the current record's "specimen_count_max" value
 * @method string          getIdentifiers()                  Returns the current record's "identifiers" value
 * @method string          getAbbreviatedIdentifiers()       Returns the current record's "abbreviated_identifiers" value
 * @method string          getIdentificationYear()           Returns the current record's "identification_year" value
 * @method float           getLongitude()                    Returns the current record's "longitude" value
 * @method float           getLatitude()                     Returns the current record's "latitude" value
 * @method string          getLongitudeVarchar()             Returns the current record's "longitude_varchar" value
 * @method string          getLatitudeVarchar()              Returns the current record's "latitude_varchar" value
 * @method string          getGtuCountryTagValue()           Returns the current record's "gtu_country_tag_value" value
 * @method string          getGtuProvinceTagValue()          Returns the current record's "gtu_province_tag_value" value
 * @method string          getMunicipality()                 Returns the current record's "municipality" value
 * @method string          getGtuOthersTagValue()            Returns the current record's "gtu_others_tag_value" value
 * @method string          getGtuCode()                      Returns the current record's "gtu_code" value
 * @method float           getGtuElevation()                 Returns the current record's "gtu_elevation" value
 * @method float           getCollectingYearFrom()           Returns the current record's "collecting_year_from" value
 * @method float           getCollectingMonthFrom()          Returns the current record's "collecting_month_from" value
 * @method float           getCollectingDayFrom()            Returns the current record's "collecting_day_from" value
 * @method float           getCollectingYearTo()             Returns the current record's "collecting_year_to" value
 * @method float           getCollectingMonthTo()            Returns the current record's "collecting_month_to" value
 * @method float           getCollectingDayTo()              Returns the current record's "collecting_day_to" value
 * @method string          getPropertiesLocality()           Returns the current record's "properties_locality" value
 * @method string          getCollectors()                   Returns the current record's "collectors" value
 * @method string          getAbbreviatedCollectors()        Returns the current record's "abbreviated_collectors" value
 * @method string          getExpeditionName()               Returns the current record's "expedition_name" value
 * @method string          getDonators()                     Returns the current record's "donators" value
 * @method string          getAbbreviatedDonators()          Returns the current record's "abbreviated_donators" value
 * @method string          getAcquisitionCategory()          Returns the current record's "acquisition_category" value
 * @method string          getAcquisitionDate()              Returns the current record's "acquisition_date" value
 * @method string          getSex()                          Returns the current record's "sex" value
 * @method string          getStage()                        Returns the current record's "stage" value
 * @method string          getState()                        Returns the current record's "state" value
 * @method integer         getSpecimenCountMalesMin()        Returns the current record's "specimen_count_males_min" value
 * @method integer         getSpecimenCountMalesMax()        Returns the current record's "specimen_count_males_max" value
 * @method integer         getSpecimenCountFemalesMin()      Returns the current record's "specimen_count_females_min" value
 * @method integer         getSpecimenCountFemalesMax()      Returns the current record's "specimen_count_females_max" value
 * @method integer         getSpecimenCountJuvenilesMin()    Returns the current record's "specimen_count_juveniles_min" value
 * @method integer         getSpecimenCountJuvenilesMax()    Returns the current record's "specimen_count_juveniles_max" value
 * @method string          getSocialStatus()                 Returns the current record's "social_status" value
 * @method string          getSpecimenPart()                 Returns the current record's "specimen_part" value
 * @method boolean         getComplete()                     Returns the current record's "complete" value
 * @method string          getObjectName()                   Returns the current record's "object_name" value
 * @method string          getSpecimenStatus()               Returns the current record's "specimen_status" value
 * @method string          getContainerStorage()             Returns the current record's "container_storage" value
 * @method string          getMethod()                       Returns the current record's "method" value
 * @method string          getTool()                         Returns the current record's "tool" value
 * @method string          getComment()                      Returns the current record's "comment" value
 * @method string          getPropertiesAll()                Returns the current record's "properties_all" value
 * @method text            getSpecimenCreationDate()         Returns the current record's "specimen_creation_date" value
 * @method string          getBuilding()                     Returns the current record's "building" value
 * @method string          getFloor()                        Returns the current record's "floor" value
 * @method string          getRoom()                         Returns the current record's "room" value
 * @method string          getRow()                          Returns the current record's "row" value
 * @method string          getShelf()                        Returns the current record's "shelf" value
 * @method string          getContainer()                    Returns the current record's "container" value
 * @method string          getSubContainer()                 Returns the current record's "sub_container" value
 * @method ReportSpecimens setId()                           Sets the current record's "id" value
 * @method ReportSpecimens setQueryId()                      Sets the current record's "query_id" value
 * @method ReportSpecimens setCreationDate()                 Sets the current record's "creation_date" value
 * @method ReportSpecimens setIdSpecimen()                   Sets the current record's "id_specimen" value
 * @method ReportSpecimens setCollectionCode()               Sets the current record's "collection_code" value
 * @method ReportSpecimens setCode()                         Sets the current record's "code" value
 * @method ReportSpecimens setAdditionalCodes()              Sets the current record's "additional_codes" value
 * @method ReportSpecimens setUuid()                         Sets the current record's "uuid" value
 * @method ReportSpecimens setIgNum()                        Sets the current record's "ig_num" value
 * @method ReportSpecimens setTaxonName()                    Sets the current record's "taxon_name" value
 * @method ReportSpecimens setAuthor()                       Sets the current record's "author" value
 * @method ReportSpecimens setFullScientificName()           Sets the current record's "full_scientific_name" value
 * @method ReportSpecimens setFamily()                       Sets the current record's "family" value
 * @method ReportSpecimens setType()                         Sets the current record's "type" value
 * @method ReportSpecimens setSpecimenCountMin()             Sets the current record's "specimen_count_min" value
 * @method ReportSpecimens setSpecimenCountMax()             Sets the current record's "specimen_count_max" value
 * @method ReportSpecimens setIdentifiers()                  Sets the current record's "identifiers" value
 * @method ReportSpecimens setAbbreviatedIdentifiers()       Sets the current record's "abbreviated_identifiers" value
 * @method ReportSpecimens setIdentificationYear()           Sets the current record's "identification_year" value
 * @method ReportSpecimens setLongitude()                    Sets the current record's "longitude" value
 * @method ReportSpecimens setLatitude()                     Sets the current record's "latitude" value
 * @method ReportSpecimens setLongitudeVarchar()             Sets the current record's "longitude_varchar" value
 * @method ReportSpecimens setLatitudeVarchar()              Sets the current record's "latitude_varchar" value
 * @method ReportSpecimens setGtuCountryTagValue()           Sets the current record's "gtu_country_tag_value" value
 * @method ReportSpecimens setGtuProvinceTagValue()          Sets the current record's "gtu_province_tag_value" value
 * @method ReportSpecimens setMunicipality()                 Sets the current record's "municipality" value
 * @method ReportSpecimens setGtuOthersTagValue()            Sets the current record's "gtu_others_tag_value" value
 * @method ReportSpecimens setGtuCode()                      Sets the current record's "gtu_code" value
 * @method ReportSpecimens setGtuElevation()                 Sets the current record's "gtu_elevation" value
 * @method ReportSpecimens setCollectingYearFrom()           Sets the current record's "collecting_year_from" value
 * @method ReportSpecimens setCollectingMonthFrom()          Sets the current record's "collecting_month_from" value
 * @method ReportSpecimens setCollectingDayFrom()            Sets the current record's "collecting_day_from" value
 * @method ReportSpecimens setCollectingYearTo()             Sets the current record's "collecting_year_to" value
 * @method ReportSpecimens setCollectingMonthTo()            Sets the current record's "collecting_month_to" value
 * @method ReportSpecimens setCollectingDayTo()              Sets the current record's "collecting_day_to" value
 * @method ReportSpecimens setPropertiesLocality()           Sets the current record's "properties_locality" value
 * @method ReportSpecimens setCollectors()                   Sets the current record's "collectors" value
 * @method ReportSpecimens setAbbreviatedCollectors()        Sets the current record's "abbreviated_collectors" value
 * @method ReportSpecimens setExpeditionName()               Sets the current record's "expedition_name" value
 * @method ReportSpecimens setDonators()                     Sets the current record's "donators" value
 * @method ReportSpecimens setAbbreviatedDonators()          Sets the current record's "abbreviated_donators" value
 * @method ReportSpecimens setAcquisitionCategory()          Sets the current record's "acquisition_category" value
 * @method ReportSpecimens setAcquisitionDate()              Sets the current record's "acquisition_date" value
 * @method ReportSpecimens setSex()                          Sets the current record's "sex" value
 * @method ReportSpecimens setStage()                        Sets the current record's "stage" value
 * @method ReportSpecimens setState()                        Sets the current record's "state" value
 * @method ReportSpecimens setSpecimenCountMalesMin()        Sets the current record's "specimen_count_males_min" value
 * @method ReportSpecimens setSpecimenCountMalesMax()        Sets the current record's "specimen_count_males_max" value
 * @method ReportSpecimens setSpecimenCountFemalesMin()      Sets the current record's "specimen_count_females_min" value
 * @method ReportSpecimens setSpecimenCountFemalesMax()      Sets the current record's "specimen_count_females_max" value
 * @method ReportSpecimens setSpecimenCountJuvenilesMin()    Sets the current record's "specimen_count_juveniles_min" value
 * @method ReportSpecimens setSpecimenCountJuvenilesMax()    Sets the current record's "specimen_count_juveniles_max" value
 * @method ReportSpecimens setSocialStatus()                 Sets the current record's "social_status" value
 * @method ReportSpecimens setSpecimenPart()                 Sets the current record's "specimen_part" value
 * @method ReportSpecimens setComplete()                     Sets the current record's "complete" value
 * @method ReportSpecimens setObjectName()                   Sets the current record's "object_name" value
 * @method ReportSpecimens setSpecimenStatus()               Sets the current record's "specimen_status" value
 * @method ReportSpecimens setContainerStorage()             Sets the current record's "container_storage" value
 * @method ReportSpecimens setMethod()                       Sets the current record's "method" value
 * @method ReportSpecimens setTool()                         Sets the current record's "tool" value
 * @method ReportSpecimens setComment()                      Sets the current record's "comment" value
 * @method ReportSpecimens setPropertiesAll()                Sets the current record's "properties_all" value
 * @method ReportSpecimens setSpecimenCreationDate()         Sets the current record's "specimen_creation_date" value
 * @method ReportSpecimens setBuilding()                     Sets the current record's "building" value
 * @method ReportSpecimens setFloor()                        Sets the current record's "floor" value
 * @method ReportSpecimens setRoom()                         Sets the current record's "room" value
 * @method ReportSpecimens setRow()                          Sets the current record's "row" value
 * @method ReportSpecimens setShelf()                        Sets the current record's "shelf" value
 * @method ReportSpecimens setContainer()                    Sets the current record's "container" value
 * @method ReportSpecimens setSubContainer()                 Sets the current record's "sub_container" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReportSpecimens extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('report_specimens');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('query_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('creation_date', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('id_specimen', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('collection_code', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('code', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('additional_codes', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('uuid', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ig_num', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('taxon_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('author', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('full_scientific_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('family', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_count_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_count_max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('identifiers', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('abbreviated_identifiers', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('identification_year', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('longitude_varchar', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('latitude_varchar', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_country_tag_value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_province_tag_value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('municipality', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_others_tag_value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_code', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_elevation', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('collecting_year_from', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('collecting_month_from', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('collecting_day_from', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('collecting_year_to', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('collecting_month_to', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('collecting_day_to', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('properties_locality', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('collectors', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('abbreviated_collectors', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('expedition_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('donators', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('abbreviated_donators', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('acquisition_category', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('acquisition_date', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('sex', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('stage', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('state', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_count_males_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_count_males_max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_count_females_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_count_females_max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_count_juveniles_min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_count_juveniles_max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('social_status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_part', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('complete', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
        $this->hasColumn('object_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('container_storage', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('method', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tool', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('properties_all', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('specimen_creation_date', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('building', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('floor', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('room', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('row', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('shelf', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('container', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('sub_container', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}