<?php

/**
 * BaseTemporalInformation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $gtu_ref
 * @property integer $specimen_ref
 * @property integer $from_date_mask
 * @property string $from_date
 * @property integer $to_date_mask
 * @property string $to_date
 * @property Doctrine_Collection $Specimens
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getGtuRef()         Returns the current record's "gtu_ref" value
 * @method integer             getSpecimenRef()    Returns the current record's "specimen_ref" value
 * @method integer             getFromDateMask()   Returns the current record's "from_date_mask" value
 * @method string              getFromDate()       Returns the current record's "from_date" value
 * @method integer             getToDateMask()     Returns the current record's "to_date_mask" value
 * @method string              getToDate()         Returns the current record's "to_date" value
 * @method Doctrine_Collection getSpecimens()      Returns the current record's "Specimens" collection
 * @method TemporalInformation setId()             Sets the current record's "id" value
 * @method TemporalInformation setGtuRef()         Sets the current record's "gtu_ref" value
 * @method TemporalInformation setSpecimenRef()    Sets the current record's "specimen_ref" value
 * @method TemporalInformation setFromDateMask()   Sets the current record's "from_date_mask" value
 * @method TemporalInformation setFromDate()       Sets the current record's "from_date" value
 * @method TemporalInformation setToDateMask()     Sets the current record's "to_date_mask" value
 * @method TemporalInformation setToDate()         Sets the current record's "to_date" value
 * @method TemporalInformation setSpecimens()      Sets the current record's "Specimens" collection
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemporalInformation extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('temporal_information');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('gtu_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('specimen_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('from_date_mask', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('from_date', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '0001-01-01',
             ));
        $this->hasColumn('to_date_mask', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('to_date', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '2038-12-31',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Specimens', array(
             'local' => 'specimen_ref',
             'foreign' => 'id'));
    }
}