<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TvReportingCountAllSpecimensByCollectionYearIg', 'doctrine');

/**
 * BaseTvReportingCountAllSpecimensByCollectionYearIg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $collection_name
 * @property string $collection_path
 * @property integer $collection_ref
 * @property float $year
 * @property timestamp $specimen_creation_date
 * @property integer $nb_records
 * @property integer $specimen_count_min
 * @property integer $specimen_count_max
 * @property integer $ig_ref
 * @property string $ig_num
 * 
 * @method integer                                        getId()                     Returns the current record's "id" value
 * @method string                                         getCollectionName()         Returns the current record's "collection_name" value
 * @method string                                         getCollectionPath()         Returns the current record's "collection_path" value
 * @method integer                                        getCollectionRef()          Returns the current record's "collection_ref" value
 * @method float                                          getYear()                   Returns the current record's "year" value
 * @method timestamp                                      getSpecimenCreationDate()   Returns the current record's "specimen_creation_date" value
 * @method integer                                        getNbRecords()              Returns the current record's "nb_records" value
 * @method integer                                        getSpecimenCountMin()       Returns the current record's "specimen_count_min" value
 * @method integer                                        getSpecimenCountMax()       Returns the current record's "specimen_count_max" value
 * @method integer                                        getIgRef()                  Returns the current record's "ig_ref" value
 * @method string                                         getIgNum()                  Returns the current record's "ig_num" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setId()                     Sets the current record's "id" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setCollectionName()         Sets the current record's "collection_name" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setCollectionPath()         Sets the current record's "collection_path" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setCollectionRef()          Sets the current record's "collection_ref" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setYear()                   Sets the current record's "year" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setSpecimenCreationDate()   Sets the current record's "specimen_creation_date" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setNbRecords()              Sets the current record's "nb_records" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setSpecimenCountMin()       Sets the current record's "specimen_count_min" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setSpecimenCountMax()       Sets the current record's "specimen_count_max" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setIgRef()                  Sets the current record's "ig_ref" value
 * @method TvReportingCountAllSpecimensByCollectionYearIg setIgNum()                  Sets the current record's "ig_num" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvReportingCountAllSpecimensByCollectionYearIg extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_reporting_count_all_specimens_by_collection_year_ig');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('collection_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('collection_path', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('collection_ref', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('year', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('specimen_creation_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('nb_records', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('specimen_count_min', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('specimen_count_max', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('ig_ref', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ig_num', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}