<?php

/**
 * BaseSpecimensMaincodes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code_main
 * @property string $category
 * @property integer $collection_ref
 * @property integer $expedition_ref
 * @property integer $gtu_ref
 * @property integer $taxon_ref
 * @property integer $litho_ref
 * @property integer $chrono_ref
 * @property integer $lithology_ref
 * @property integer $mineral_ref
 * @property string $acquisition_category
 * @property integer $acquisition_date_mask
 * @property string $acquisition_date
 * @property boolean $station_visible
 * @property integer $ig_ref
 * @property string $spec_coll_ids
 * @property string $spec_ident_ids
 * @property string $spec_don_sel_ids
 * @property string $collection_type
 * @property string $collection_code
 * @property string $collection_name
 * @property boolean $collection_is_public
 * @property integer $collection_parent_ref
 * @property string $collection_path
 * @property string $expedition_name
 * @property string $expedition_name_indexed
 * @property string $gtu_code
 * @property integer $gtu_from_date_mask
 * @property string $gtu_from_date
 * @property integer $gtu_to_date_mask
 * @property string $gtu_to_date
 * @property string $gtu_tag_values_indexed
 * @property string $gtu_country_tag_indexed
 * @property string $gtu_country_tag_value
 * @property string $gtu_location
 * @property float $gtu_elevation
 * @property float $gtu_elevation_accuracy
 * @property string $taxon_name
 * @property string $taxon_name_indexed
 * @property integer $taxon_level_ref
 * @property string $taxon_level_name
 * @property string $taxon_status
 * @property string $taxon_path
 * @property integer $taxon_parent_ref
 * @property boolean $taxon_extinct
 * @property string $litho_name
 * @property string $litho_name_indexed
 * @property integer $litho_level_ref
 * @property string $litho_level_name
 * @property string $litho_status
 * @property boolean $litho_local
 * @property string $litho_color
 * @property string $litho_path
 * @property integer $litho_parent_ref
 * @property string $chrono_name
 * @property string $chrono_name_indexed
 * @property integer $chrono_level_ref
 * @property string $chrono_level_name
 * @property string $chrono_status
 * @property boolean $chrono_local
 * @property string $chrono_color
 * @property string $chrono_path
 * @property integer $chrono_parent_ref
 * @property string $lithology_name
 * @property string $lithology_name_indexed
 * @property integer $lithology_level_ref
 * @property string $lithology_level_name
 * @property string $lithology_status
 * @property boolean $lithology_local
 * @property string $lithology_color
 * @property string $lithology_path
 * @property integer $lithology_parent_ref
 * @property string $mineral_name
 * @property string $mineral_name_indexed
 * @property integer $mineral_level_ref
 * @property string $mineral_level_name
 * @property string $mineral_status
 * @property boolean $mineral_local
 * @property string $mineral_color
 * @property string $mineral_path
 * @property integer $mineral_parent_ref
 * @property string $ig_num
 * @property string $ig_num_indexed
 * @property integer $ig_date_mask
 * @property string $type
 * @property string $type_group
 * @property string $type_search
 * @property string $sex
 * @property string $stage
 * @property string $state
 * @property string $social_status
 * @property string $rock_form
 * @property string $specimen_part
 * @property boolean $complete
 * @property integer $institution_ref
 * @property string $building
 * @property string $floor
 * @property string $room
 * @property string $row
 * @property string $col
 * @property string $shelf
 * @property string $container
 * @property string $sub_container
 * @property string $container_type
 * @property string $sub_container_type
 * @property string $container_storage
 * @property string $sub_container_storage
 * @property boolean $surnumerary
 * @property string $specimen_status
 * @property integer $specimen_count_min
 * @property integer $specimen_count_max
 * @property string $object_name
 * @property string $object_name_indexed
 * @property Collections $Collections
 * @property Expeditions $Expeditions
 * @property Gtu $Gtu
 * @property Taxonomy $Taxonomy
 * @property Lithostratigraphy $Lithostratigraphy
 * @property Chronostratigraphy $Chronostratigraphy
 * @property Lithology $Lithology
 * @property Mineralogy $Mineralogy
 * @property Igs $Igs
 * @property Institutions $Institution
 * @property Doctrine_Collection $CollectingMethods
 * @property Doctrine_Collection $CollectingTools
 * @property SubComments $SubComments
 * @property SubProperties $SubProperties
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method string              getCodeMain()                Returns the current record's "code_main" value
 * @method string              getCategory()                Returns the current record's "category" value
 * @method integer             getCollectionRef()           Returns the current record's "collection_ref" value
 * @method integer             getExpeditionRef()           Returns the current record's "expedition_ref" value
 * @method integer             getGtuRef()                  Returns the current record's "gtu_ref" value
 * @method integer             getTaxonRef()                Returns the current record's "taxon_ref" value
 * @method integer             getLithoRef()                Returns the current record's "litho_ref" value
 * @method integer             getChronoRef()               Returns the current record's "chrono_ref" value
 * @method integer             getLithologyRef()            Returns the current record's "lithology_ref" value
 * @method integer             getMineralRef()              Returns the current record's "mineral_ref" value
 * @method string              getAcquisitionCategory()     Returns the current record's "acquisition_category" value
 * @method integer             getAcquisitionDateMask()     Returns the current record's "acquisition_date_mask" value
 * @method string              getAcquisitionDate()         Returns the current record's "acquisition_date" value
 * @method boolean             getStationVisible()          Returns the current record's "station_visible" value
 * @method integer             getIgRef()                   Returns the current record's "ig_ref" value
 * @method string              getSpecCollIds()             Returns the current record's "spec_coll_ids" value
 * @method string              getSpecIdentIds()            Returns the current record's "spec_ident_ids" value
 * @method string              getSpecDonSelIds()           Returns the current record's "spec_don_sel_ids" value
 * @method string              getCollectionType()          Returns the current record's "collection_type" value
 * @method string              getCollectionCode()          Returns the current record's "collection_code" value
 * @method string              getCollectionName()          Returns the current record's "collection_name" value
 * @method boolean             getCollectionIsPublic()      Returns the current record's "collection_is_public" value
 * @method integer             getCollectionParentRef()     Returns the current record's "collection_parent_ref" value
 * @method string              getCollectionPath()          Returns the current record's "collection_path" value
 * @method string              getExpeditionName()          Returns the current record's "expedition_name" value
 * @method string              getExpeditionNameIndexed()   Returns the current record's "expedition_name_indexed" value
 * @method string              getGtuCode()                 Returns the current record's "gtu_code" value
 * @method integer             getGtuFromDateMask()         Returns the current record's "gtu_from_date_mask" value
 * @method string              getGtuFromDate()             Returns the current record's "gtu_from_date" value
 * @method integer             getGtuToDateMask()           Returns the current record's "gtu_to_date_mask" value
 * @method string              getGtuToDate()               Returns the current record's "gtu_to_date" value
 * @method string              getGtuTagValuesIndexed()     Returns the current record's "gtu_tag_values_indexed" value
 * @method string              getGtuCountryTagIndexed()    Returns the current record's "gtu_country_tag_indexed" value
 * @method string              getGtuCountryTagValue()      Returns the current record's "gtu_country_tag_value" value
 * @method string              getGtuLocation()             Returns the current record's "gtu_location" value
 * @method float               getGtuElevation()            Returns the current record's "gtu_elevation" value
 * @method float               getGtuElevationAccuracy()    Returns the current record's "gtu_elevation_accuracy" value
 * @method string              getTaxonName()               Returns the current record's "taxon_name" value
 * @method string              getTaxonNameIndexed()        Returns the current record's "taxon_name_indexed" value
 * @method integer             getTaxonLevelRef()           Returns the current record's "taxon_level_ref" value
 * @method string              getTaxonLevelName()          Returns the current record's "taxon_level_name" value
 * @method string              getTaxonStatus()             Returns the current record's "taxon_status" value
 * @method string              getTaxonPath()               Returns the current record's "taxon_path" value
 * @method integer             getTaxonParentRef()          Returns the current record's "taxon_parent_ref" value
 * @method boolean             getTaxonExtinct()            Returns the current record's "taxon_extinct" value
 * @method string              getLithoName()               Returns the current record's "litho_name" value
 * @method string              getLithoNameIndexed()        Returns the current record's "litho_name_indexed" value
 * @method integer             getLithoLevelRef()           Returns the current record's "litho_level_ref" value
 * @method string              getLithoLevelName()          Returns the current record's "litho_level_name" value
 * @method string              getLithoStatus()             Returns the current record's "litho_status" value
 * @method boolean             getLithoLocal()              Returns the current record's "litho_local" value
 * @method string              getLithoColor()              Returns the current record's "litho_color" value
 * @method string              getLithoPath()               Returns the current record's "litho_path" value
 * @method integer             getLithoParentRef()          Returns the current record's "litho_parent_ref" value
 * @method string              getChronoName()              Returns the current record's "chrono_name" value
 * @method string              getChronoNameIndexed()       Returns the current record's "chrono_name_indexed" value
 * @method integer             getChronoLevelRef()          Returns the current record's "chrono_level_ref" value
 * @method string              getChronoLevelName()         Returns the current record's "chrono_level_name" value
 * @method string              getChronoStatus()            Returns the current record's "chrono_status" value
 * @method boolean             getChronoLocal()             Returns the current record's "chrono_local" value
 * @method string              getChronoColor()             Returns the current record's "chrono_color" value
 * @method string              getChronoPath()              Returns the current record's "chrono_path" value
 * @method integer             getChronoParentRef()         Returns the current record's "chrono_parent_ref" value
 * @method string              getLithologyName()           Returns the current record's "lithology_name" value
 * @method string              getLithologyNameIndexed()    Returns the current record's "lithology_name_indexed" value
 * @method integer             getLithologyLevelRef()       Returns the current record's "lithology_level_ref" value
 * @method string              getLithologyLevelName()      Returns the current record's "lithology_level_name" value
 * @method string              getLithologyStatus()         Returns the current record's "lithology_status" value
 * @method boolean             getLithologyLocal()          Returns the current record's "lithology_local" value
 * @method string              getLithologyColor()          Returns the current record's "lithology_color" value
 * @method string              getLithologyPath()           Returns the current record's "lithology_path" value
 * @method integer             getLithologyParentRef()      Returns the current record's "lithology_parent_ref" value
 * @method string              getMineralName()             Returns the current record's "mineral_name" value
 * @method string              getMineralNameIndexed()      Returns the current record's "mineral_name_indexed" value
 * @method integer             getMineralLevelRef()         Returns the current record's "mineral_level_ref" value
 * @method string              getMineralLevelName()        Returns the current record's "mineral_level_name" value
 * @method string              getMineralStatus()           Returns the current record's "mineral_status" value
 * @method boolean             getMineralLocal()            Returns the current record's "mineral_local" value
 * @method string              getMineralColor()            Returns the current record's "mineral_color" value
 * @method string              getMineralPath()             Returns the current record's "mineral_path" value
 * @method integer             getMineralParentRef()        Returns the current record's "mineral_parent_ref" value
 * @method string              getIgNum()                   Returns the current record's "ig_num" value
 * @method string              getIgNumIndexed()            Returns the current record's "ig_num_indexed" value
 * @method integer             getIgDateMask()              Returns the current record's "ig_date_mask" value
 * @method string              getType()                    Returns the current record's "type" value
 * @method string              getTypeGroup()               Returns the current record's "type_group" value
 * @method string              getTypeSearch()              Returns the current record's "type_search" value
 * @method string              getSex()                     Returns the current record's "sex" value
 * @method string              getStage()                   Returns the current record's "stage" value
 * @method string              getState()                   Returns the current record's "state" value
 * @method string              getSocialStatus()            Returns the current record's "social_status" value
 * @method string              getRockForm()                Returns the current record's "rock_form" value
 * @method string              getSpecimenPart()            Returns the current record's "specimen_part" value
 * @method boolean             getComplete()                Returns the current record's "complete" value
 * @method integer             getInstitutionRef()          Returns the current record's "institution_ref" value
 * @method string              getBuilding()                Returns the current record's "building" value
 * @method string              getFloor()                   Returns the current record's "floor" value
 * @method string              getRoom()                    Returns the current record's "room" value
 * @method string              getRow()                     Returns the current record's "row" value
 * @method string              getCol()                     Returns the current record's "col" value
 * @method string              getShelf()                   Returns the current record's "shelf" value
 * @method string              getContainer()               Returns the current record's "container" value
 * @method string              getSubContainer()            Returns the current record's "sub_container" value
 * @method string              getContainerType()           Returns the current record's "container_type" value
 * @method string              getSubContainerType()        Returns the current record's "sub_container_type" value
 * @method string              getContainerStorage()        Returns the current record's "container_storage" value
 * @method string              getSubContainerStorage()     Returns the current record's "sub_container_storage" value
 * @method boolean             getSurnumerary()             Returns the current record's "surnumerary" value
 * @method string              getSpecimenStatus()          Returns the current record's "specimen_status" value
 * @method integer             getSpecimenCountMin()        Returns the current record's "specimen_count_min" value
 * @method integer             getSpecimenCountMax()        Returns the current record's "specimen_count_max" value
 * @method string              getObjectName()              Returns the current record's "object_name" value
 * @method string              getObjectNameIndexed()       Returns the current record's "object_name_indexed" value
 * @method Collections         getCollections()             Returns the current record's "Collections" value
 * @method Expeditions         getExpeditions()             Returns the current record's "Expeditions" value
 * @method Gtu                 getGtu()                     Returns the current record's "Gtu" value
 * @method Taxonomy            getTaxonomy()                Returns the current record's "Taxonomy" value
 * @method Lithostratigraphy   getLithostratigraphy()       Returns the current record's "Lithostratigraphy" value
 * @method Chronostratigraphy  getChronostratigraphy()      Returns the current record's "Chronostratigraphy" value
 * @method Lithology           getLithology()               Returns the current record's "Lithology" value
 * @method Mineralogy          getMineralogy()              Returns the current record's "Mineralogy" value
 * @method Igs                 getIgs()                     Returns the current record's "Igs" value
 * @method Institutions        getInstitution()             Returns the current record's "Institution" value
 * @method Doctrine_Collection getCollectingMethods()       Returns the current record's "CollectingMethods" collection
 * @method Doctrine_Collection getCollectingTools()         Returns the current record's "CollectingTools" collection
 * @method SubComments         getSubComments()             Returns the current record's "SubComments" value
 * @method SubProperties       getSubProperties()           Returns the current record's "SubProperties" value
 * @method SpecimensMaincodes  setId()                      Sets the current record's "id" value
 * @method SpecimensMaincodes  setCodeMain()                Sets the current record's "code_main" value
 * @method SpecimensMaincodes  setCategory()                Sets the current record's "category" value
 * @method SpecimensMaincodes  setCollectionRef()           Sets the current record's "collection_ref" value
 * @method SpecimensMaincodes  setExpeditionRef()           Sets the current record's "expedition_ref" value
 * @method SpecimensMaincodes  setGtuRef()                  Sets the current record's "gtu_ref" value
 * @method SpecimensMaincodes  setTaxonRef()                Sets the current record's "taxon_ref" value
 * @method SpecimensMaincodes  setLithoRef()                Sets the current record's "litho_ref" value
 * @method SpecimensMaincodes  setChronoRef()               Sets the current record's "chrono_ref" value
 * @method SpecimensMaincodes  setLithologyRef()            Sets the current record's "lithology_ref" value
 * @method SpecimensMaincodes  setMineralRef()              Sets the current record's "mineral_ref" value
 * @method SpecimensMaincodes  setAcquisitionCategory()     Sets the current record's "acquisition_category" value
 * @method SpecimensMaincodes  setAcquisitionDateMask()     Sets the current record's "acquisition_date_mask" value
 * @method SpecimensMaincodes  setAcquisitionDate()         Sets the current record's "acquisition_date" value
 * @method SpecimensMaincodes  setStationVisible()          Sets the current record's "station_visible" value
 * @method SpecimensMaincodes  setIgRef()                   Sets the current record's "ig_ref" value
 * @method SpecimensMaincodes  setSpecCollIds()             Sets the current record's "spec_coll_ids" value
 * @method SpecimensMaincodes  setSpecIdentIds()            Sets the current record's "spec_ident_ids" value
 * @method SpecimensMaincodes  setSpecDonSelIds()           Sets the current record's "spec_don_sel_ids" value
 * @method SpecimensMaincodes  setCollectionType()          Sets the current record's "collection_type" value
 * @method SpecimensMaincodes  setCollectionCode()          Sets the current record's "collection_code" value
 * @method SpecimensMaincodes  setCollectionName()          Sets the current record's "collection_name" value
 * @method SpecimensMaincodes  setCollectionIsPublic()      Sets the current record's "collection_is_public" value
 * @method SpecimensMaincodes  setCollectionParentRef()     Sets the current record's "collection_parent_ref" value
 * @method SpecimensMaincodes  setCollectionPath()          Sets the current record's "collection_path" value
 * @method SpecimensMaincodes  setExpeditionName()          Sets the current record's "expedition_name" value
 * @method SpecimensMaincodes  setExpeditionNameIndexed()   Sets the current record's "expedition_name_indexed" value
 * @method SpecimensMaincodes  setGtuCode()                 Sets the current record's "gtu_code" value
 * @method SpecimensMaincodes  setGtuFromDateMask()         Sets the current record's "gtu_from_date_mask" value
 * @method SpecimensMaincodes  setGtuFromDate()             Sets the current record's "gtu_from_date" value
 * @method SpecimensMaincodes  setGtuToDateMask()           Sets the current record's "gtu_to_date_mask" value
 * @method SpecimensMaincodes  setGtuToDate()               Sets the current record's "gtu_to_date" value
 * @method SpecimensMaincodes  setGtuTagValuesIndexed()     Sets the current record's "gtu_tag_values_indexed" value
 * @method SpecimensMaincodes  setGtuCountryTagIndexed()    Sets the current record's "gtu_country_tag_indexed" value
 * @method SpecimensMaincodes  setGtuCountryTagValue()      Sets the current record's "gtu_country_tag_value" value
 * @method SpecimensMaincodes  setGtuLocation()             Sets the current record's "gtu_location" value
 * @method SpecimensMaincodes  setGtuElevation()            Sets the current record's "gtu_elevation" value
 * @method SpecimensMaincodes  setGtuElevationAccuracy()    Sets the current record's "gtu_elevation_accuracy" value
 * @method SpecimensMaincodes  setTaxonName()               Sets the current record's "taxon_name" value
 * @method SpecimensMaincodes  setTaxonNameIndexed()        Sets the current record's "taxon_name_indexed" value
 * @method SpecimensMaincodes  setTaxonLevelRef()           Sets the current record's "taxon_level_ref" value
 * @method SpecimensMaincodes  setTaxonLevelName()          Sets the current record's "taxon_level_name" value
 * @method SpecimensMaincodes  setTaxonStatus()             Sets the current record's "taxon_status" value
 * @method SpecimensMaincodes  setTaxonPath()               Sets the current record's "taxon_path" value
 * @method SpecimensMaincodes  setTaxonParentRef()          Sets the current record's "taxon_parent_ref" value
 * @method SpecimensMaincodes  setTaxonExtinct()            Sets the current record's "taxon_extinct" value
 * @method SpecimensMaincodes  setLithoName()               Sets the current record's "litho_name" value
 * @method SpecimensMaincodes  setLithoNameIndexed()        Sets the current record's "litho_name_indexed" value
 * @method SpecimensMaincodes  setLithoLevelRef()           Sets the current record's "litho_level_ref" value
 * @method SpecimensMaincodes  setLithoLevelName()          Sets the current record's "litho_level_name" value
 * @method SpecimensMaincodes  setLithoStatus()             Sets the current record's "litho_status" value
 * @method SpecimensMaincodes  setLithoLocal()              Sets the current record's "litho_local" value
 * @method SpecimensMaincodes  setLithoColor()              Sets the current record's "litho_color" value
 * @method SpecimensMaincodes  setLithoPath()               Sets the current record's "litho_path" value
 * @method SpecimensMaincodes  setLithoParentRef()          Sets the current record's "litho_parent_ref" value
 * @method SpecimensMaincodes  setChronoName()              Sets the current record's "chrono_name" value
 * @method SpecimensMaincodes  setChronoNameIndexed()       Sets the current record's "chrono_name_indexed" value
 * @method SpecimensMaincodes  setChronoLevelRef()          Sets the current record's "chrono_level_ref" value
 * @method SpecimensMaincodes  setChronoLevelName()         Sets the current record's "chrono_level_name" value
 * @method SpecimensMaincodes  setChronoStatus()            Sets the current record's "chrono_status" value
 * @method SpecimensMaincodes  setChronoLocal()             Sets the current record's "chrono_local" value
 * @method SpecimensMaincodes  setChronoColor()             Sets the current record's "chrono_color" value
 * @method SpecimensMaincodes  setChronoPath()              Sets the current record's "chrono_path" value
 * @method SpecimensMaincodes  setChronoParentRef()         Sets the current record's "chrono_parent_ref" value
 * @method SpecimensMaincodes  setLithologyName()           Sets the current record's "lithology_name" value
 * @method SpecimensMaincodes  setLithologyNameIndexed()    Sets the current record's "lithology_name_indexed" value
 * @method SpecimensMaincodes  setLithologyLevelRef()       Sets the current record's "lithology_level_ref" value
 * @method SpecimensMaincodes  setLithologyLevelName()      Sets the current record's "lithology_level_name" value
 * @method SpecimensMaincodes  setLithologyStatus()         Sets the current record's "lithology_status" value
 * @method SpecimensMaincodes  setLithologyLocal()          Sets the current record's "lithology_local" value
 * @method SpecimensMaincodes  setLithologyColor()          Sets the current record's "lithology_color" value
 * @method SpecimensMaincodes  setLithologyPath()           Sets the current record's "lithology_path" value
 * @method SpecimensMaincodes  setLithologyParentRef()      Sets the current record's "lithology_parent_ref" value
 * @method SpecimensMaincodes  setMineralName()             Sets the current record's "mineral_name" value
 * @method SpecimensMaincodes  setMineralNameIndexed()      Sets the current record's "mineral_name_indexed" value
 * @method SpecimensMaincodes  setMineralLevelRef()         Sets the current record's "mineral_level_ref" value
 * @method SpecimensMaincodes  setMineralLevelName()        Sets the current record's "mineral_level_name" value
 * @method SpecimensMaincodes  setMineralStatus()           Sets the current record's "mineral_status" value
 * @method SpecimensMaincodes  setMineralLocal()            Sets the current record's "mineral_local" value
 * @method SpecimensMaincodes  setMineralColor()            Sets the current record's "mineral_color" value
 * @method SpecimensMaincodes  setMineralPath()             Sets the current record's "mineral_path" value
 * @method SpecimensMaincodes  setMineralParentRef()        Sets the current record's "mineral_parent_ref" value
 * @method SpecimensMaincodes  setIgNum()                   Sets the current record's "ig_num" value
 * @method SpecimensMaincodes  setIgNumIndexed()            Sets the current record's "ig_num_indexed" value
 * @method SpecimensMaincodes  setIgDateMask()              Sets the current record's "ig_date_mask" value
 * @method SpecimensMaincodes  setType()                    Sets the current record's "type" value
 * @method SpecimensMaincodes  setTypeGroup()               Sets the current record's "type_group" value
 * @method SpecimensMaincodes  setTypeSearch()              Sets the current record's "type_search" value
 * @method SpecimensMaincodes  setSex()                     Sets the current record's "sex" value
 * @method SpecimensMaincodes  setStage()                   Sets the current record's "stage" value
 * @method SpecimensMaincodes  setState()                   Sets the current record's "state" value
 * @method SpecimensMaincodes  setSocialStatus()            Sets the current record's "social_status" value
 * @method SpecimensMaincodes  setRockForm()                Sets the current record's "rock_form" value
 * @method SpecimensMaincodes  setSpecimenPart()            Sets the current record's "specimen_part" value
 * @method SpecimensMaincodes  setComplete()                Sets the current record's "complete" value
 * @method SpecimensMaincodes  setInstitutionRef()          Sets the current record's "institution_ref" value
 * @method SpecimensMaincodes  setBuilding()                Sets the current record's "building" value
 * @method SpecimensMaincodes  setFloor()                   Sets the current record's "floor" value
 * @method SpecimensMaincodes  setRoom()                    Sets the current record's "room" value
 * @method SpecimensMaincodes  setRow()                     Sets the current record's "row" value
 * @method SpecimensMaincodes  setCol()                     Sets the current record's "col" value
 * @method SpecimensMaincodes  setShelf()                   Sets the current record's "shelf" value
 * @method SpecimensMaincodes  setContainer()               Sets the current record's "container" value
 * @method SpecimensMaincodes  setSubContainer()            Sets the current record's "sub_container" value
 * @method SpecimensMaincodes  setContainerType()           Sets the current record's "container_type" value
 * @method SpecimensMaincodes  setSubContainerType()        Sets the current record's "sub_container_type" value
 * @method SpecimensMaincodes  setContainerStorage()        Sets the current record's "container_storage" value
 * @method SpecimensMaincodes  setSubContainerStorage()     Sets the current record's "sub_container_storage" value
 * @method SpecimensMaincodes  setSurnumerary()             Sets the current record's "surnumerary" value
 * @method SpecimensMaincodes  setSpecimenStatus()          Sets the current record's "specimen_status" value
 * @method SpecimensMaincodes  setSpecimenCountMin()        Sets the current record's "specimen_count_min" value
 * @method SpecimensMaincodes  setSpecimenCountMax()        Sets the current record's "specimen_count_max" value
 * @method SpecimensMaincodes  setObjectName()              Sets the current record's "object_name" value
 * @method SpecimensMaincodes  setObjectNameIndexed()       Sets the current record's "object_name_indexed" value
 * @method SpecimensMaincodes  setCollections()             Sets the current record's "Collections" value
 * @method SpecimensMaincodes  setExpeditions()             Sets the current record's "Expeditions" value
 * @method SpecimensMaincodes  setGtu()                     Sets the current record's "Gtu" value
 * @method SpecimensMaincodes  setTaxonomy()                Sets the current record's "Taxonomy" value
 * @method SpecimensMaincodes  setLithostratigraphy()       Sets the current record's "Lithostratigraphy" value
 * @method SpecimensMaincodes  setChronostratigraphy()      Sets the current record's "Chronostratigraphy" value
 * @method SpecimensMaincodes  setLithology()               Sets the current record's "Lithology" value
 * @method SpecimensMaincodes  setMineralogy()              Sets the current record's "Mineralogy" value
 * @method SpecimensMaincodes  setIgs()                     Sets the current record's "Igs" value
 * @method SpecimensMaincodes  setInstitution()             Sets the current record's "Institution" value
 * @method SpecimensMaincodes  setCollectingMethods()       Sets the current record's "CollectingMethods" collection
 * @method SpecimensMaincodes  setCollectingTools()         Sets the current record's "CollectingTools" collection
 * @method SpecimensMaincodes  setSubComments()             Sets the current record's "SubComments" value
 * @method SpecimensMaincodes  setSubProperties()           Sets the current record's "SubProperties" value
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpecimensMaincodes extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('specimens_maincodes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('code_main', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('category', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'physical',
             ));
        $this->hasColumn('collection_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('expedition_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gtu_ref', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('taxon_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('litho_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('chrono_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lithology_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mineral_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('acquisition_category', 'string', null, array(
             'type' => 'string',
             'default' => 'expedition',
             ));
        $this->hasColumn('acquisition_date_mask', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('acquisition_date', 'string', null, array(
             'type' => 'string',
             'default' => '0001-01-01',
             ));
        $this->hasColumn('station_visible', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ig_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('spec_coll_ids', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('spec_ident_ids', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('spec_don_sel_ids', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('collection_type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('collection_code', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('collection_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('collection_is_public', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('collection_parent_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('collection_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('expedition_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('expedition_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_code', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_from_date_mask', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gtu_from_date', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_to_date_mask', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gtu_to_date', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_tag_values_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_country_tag_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_country_tag_value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_location', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('gtu_elevation', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('gtu_elevation_accuracy', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('taxon_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('taxon_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('taxon_level_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('taxon_level_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('taxon_status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('taxon_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('taxon_parent_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('taxon_extinct', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('litho_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('litho_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('litho_level_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('litho_level_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('litho_status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('litho_local', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('litho_color', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('litho_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('litho_parent_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('chrono_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('chrono_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('chrono_level_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('chrono_level_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('chrono_status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('chrono_local', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('chrono_color', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('chrono_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('chrono_parent_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lithology_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lithology_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lithology_level_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lithology_level_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lithology_status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lithology_local', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('lithology_color', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lithology_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lithology_parent_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mineral_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mineral_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mineral_level_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mineral_level_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mineral_status', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mineral_local', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('mineral_color', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mineral_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('mineral_parent_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ig_num', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ig_num_indexed', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ig_date_mask', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'specimen',
             ));
        $this->hasColumn('type_group', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'specimen',
             ));
        $this->hasColumn('type_search', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'specimen',
             ));
        $this->hasColumn('sex', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'undefined',
             ));
        $this->hasColumn('stage', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'undefined',
             ));
        $this->hasColumn('state', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'not applicable',
             ));
        $this->hasColumn('social_status', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'not applicable',
             ));
        $this->hasColumn('rock_form', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'not applicable',
             ));
        $this->hasColumn('specimen_part', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'specimen',
             ));
        $this->hasColumn('complete', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('institution_ref', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('building', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('floor', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('room', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('row', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('col', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('shelf', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('container', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('sub_container', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('container_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'container',
             ));
        $this->hasColumn('sub_container_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'container',
             ));
        $this->hasColumn('container_storage', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'dry',
             ));
        $this->hasColumn('sub_container_storage', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'dry',
             ));
        $this->hasColumn('surnumerary', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('specimen_status', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'good state',
             ));
        $this->hasColumn('specimen_count_min', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('specimen_count_max', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('object_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('object_name_indexed', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Collections', array(
             'local' => 'collection_ref',
             'foreign' => 'id'));

        $this->hasOne('Expeditions', array(
             'local' => 'expedition_ref',
             'foreign' => 'id'));

        $this->hasOne('Gtu', array(
             'local' => 'gtu_ref',
             'foreign' => 'id'));

        $this->hasOne('Taxonomy', array(
             'local' => 'taxon_ref',
             'foreign' => 'id'));

        $this->hasOne('Lithostratigraphy', array(
             'local' => 'litho_ref',
             'foreign' => 'id'));

        $this->hasOne('Chronostratigraphy', array(
             'local' => 'chrono_ref',
             'foreign' => 'id'));

        $this->hasOne('Lithology', array(
             'local' => 'lithology_ref',
             'foreign' => 'id'));

        $this->hasOne('Mineralogy', array(
             'local' => 'mineral_ref',
             'foreign' => 'id'));

        $this->hasOne('Igs', array(
             'local' => 'ig_ref',
             'foreign' => 'id'));

        $this->hasOne('Institutions as Institution', array(
             'local' => 'institution_ref',
             'foreign' => 'id'));

        $this->hasMany('CollectingMethods', array(
             'refClass' => 'SpecimensMethods',
             'local' => 'specimen_ref',
             'foreign' => 'collecting_method_ref'));

        $this->hasMany('CollectingTools', array(
             'refClass' => 'SpecimensTools',
             'local' => 'specimen_ref',
             'foreign' => 'collecting_tool_ref'));

        $this->hasOne('SubComments', array(
             'local' => 'id',
             'foreign' => 'record_id'));

        $this->hasOne('SubProperties', array(
             'local' => 'id',
             'foreign' => 'record_id'));
    }
}