<?php

/**
 * BaseGeoref
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $source
 * @property boolean $manual_offset
 * @property string $name
 * @property string $country
 * @property string $country_iso3166
 * @property string $osm_id
 * @property string $geonames_id
 * @property string $wikidata_id
 * @property string $osm_wkt
 * @property string $osm_url
 * @property string $osm_json
 * @property string $osm_metadata_json
 * @property string $osm_geo_type
 * @property string $osm_class
 * @property string $osm_type
 * @property integer $osm_place_rank
 * @property string $epsg
 * @property string $creation_date
 * @property Doctrine_Collection $GtuToGeoref
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getSource()            Returns the current record's "source" value
 * @method boolean             getManualOffset()      Returns the current record's "manual_offset" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getCountry()           Returns the current record's "country" value
 * @method string              getCountryIso3166()    Returns the current record's "country_iso3166" value
 * @method string              getOsmId()             Returns the current record's "osm_id" value
 * @method string              getGeonamesId()        Returns the current record's "geonames_id" value
 * @method string              getWikidataId()        Returns the current record's "wikidata_id" value
 * @method string              getOsmWkt()            Returns the current record's "osm_wkt" value
 * @method string              getOsmUrl()            Returns the current record's "osm_url" value
 * @method string              getOsmJson()           Returns the current record's "osm_json" value
 * @method string              getOsmMetadataJson()   Returns the current record's "osm_metadata_json" value
 * @method string              getOsmGeoType()        Returns the current record's "osm_geo_type" value
 * @method string              getOsmClass()          Returns the current record's "osm_class" value
 * @method string              getOsmType()           Returns the current record's "osm_type" value
 * @method integer             getOsmPlaceRank()      Returns the current record's "osm_place_rank" value
 * @method string              getEpsg()              Returns the current record's "epsg" value
 * @method string              getCreationDate()      Returns the current record's "creation_date" value
 * @method Doctrine_Collection getGtuToGeoref()       Returns the current record's "GtuToGeoref" collection
 * @method Georef              setId()                Sets the current record's "id" value
 * @method Georef              setSource()            Sets the current record's "source" value
 * @method Georef              setManualOffset()      Sets the current record's "manual_offset" value
 * @method Georef              setName()              Sets the current record's "name" value
 * @method Georef              setCountry()           Sets the current record's "country" value
 * @method Georef              setCountryIso3166()    Sets the current record's "country_iso3166" value
 * @method Georef              setOsmId()             Sets the current record's "osm_id" value
 * @method Georef              setGeonamesId()        Sets the current record's "geonames_id" value
 * @method Georef              setWikidataId()        Sets the current record's "wikidata_id" value
 * @method Georef              setOsmWkt()            Sets the current record's "osm_wkt" value
 * @method Georef              setOsmUrl()            Sets the current record's "osm_url" value
 * @method Georef              setOsmJson()           Sets the current record's "osm_json" value
 * @method Georef              setOsmMetadataJson()   Sets the current record's "osm_metadata_json" value
 * @method Georef              setOsmGeoType()        Sets the current record's "osm_geo_type" value
 * @method Georef              setOsmClass()          Sets the current record's "osm_class" value
 * @method Georef              setOsmType()           Sets the current record's "osm_type" value
 * @method Georef              setOsmPlaceRank()      Sets the current record's "osm_place_rank" value
 * @method Georef              setEpsg()              Sets the current record's "epsg" value
 * @method Georef              setCreationDate()      Sets the current record's "creation_date" value
 * @method Georef              setGtuToGeoref()       Sets the current record's "GtuToGeoref" collection
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeoref extends DarwinModel
{
    public function setTableDefinition()
    {
        $this->setTableName('georef');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('source', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('manual_offset', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('country', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('country_iso3166', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_id', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('geonames_id', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('wikidata_id', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_wkt', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_json', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_metadata_json', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_geo_type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_class', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('osm_place_rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('epsg', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('creation_date', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '0001-01-01',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GtuToGeoref', array(
             'local' => 'id',
             'foreign' => 'georef_ref'));
    }
}