<?php

/**
 * ZzzRotiferSpecimens filter form base class.
 *
 * @package    darwin
 * @subpackage filter
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseZzzRotiferSpecimensFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                       => new sfWidgetFormFilterInput(),
      'category'                 => new sfWidgetFormFilterInput(),
      'collection_ref'           => new sfWidgetFormFilterInput(),
      'expedition_ref'           => new sfWidgetFormFilterInput(),
      'gtu_ref'                  => new sfWidgetFormFilterInput(),
      'taxon_ref'                => new sfWidgetFormFilterInput(),
      'litho_ref'                => new sfWidgetFormFilterInput(),
      'chrono_ref'               => new sfWidgetFormFilterInput(),
      'lithology_ref'            => new sfWidgetFormFilterInput(),
      'mineral_ref'              => new sfWidgetFormFilterInput(),
      'acquisition_category'     => new sfWidgetFormFilterInput(),
      'acquisition_date_mask'    => new sfWidgetFormFilterInput(),
      'acquisition_date'         => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'station_visible'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'ig_ref'                   => new sfWidgetFormFilterInput(),
      'type'                     => new sfWidgetFormFilterInput(),
      'type_group'               => new sfWidgetFormFilterInput(),
      'type_search'              => new sfWidgetFormFilterInput(),
      'sex'                      => new sfWidgetFormFilterInput(),
      'stage'                    => new sfWidgetFormFilterInput(),
      'state'                    => new sfWidgetFormFilterInput(),
      'social_status'            => new sfWidgetFormFilterInput(),
      'rock_form'                => new sfWidgetFormFilterInput(),
      'specimen_part'            => new sfWidgetFormFilterInput(),
      'complete'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'institution_ref'          => new sfWidgetFormFilterInput(),
      'building'                 => new sfWidgetFormFilterInput(),
      'floor'                    => new sfWidgetFormFilterInput(),
      'room'                     => new sfWidgetFormFilterInput(),
      'row'                      => new sfWidgetFormFilterInput(),
      'shelf'                    => new sfWidgetFormFilterInput(),
      'container'                => new sfWidgetFormFilterInput(),
      'sub_container'            => new sfWidgetFormFilterInput(),
      'container_type'           => new sfWidgetFormFilterInput(),
      'sub_container_type'       => new sfWidgetFormFilterInput(),
      'container_storage'        => new sfWidgetFormFilterInput(),
      'sub_container_storage'    => new sfWidgetFormFilterInput(),
      'surnumerary'              => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'specimen_status'          => new sfWidgetFormFilterInput(),
      'specimen_count_min'       => new sfWidgetFormFilterInput(),
      'specimen_count_max'       => new sfWidgetFormFilterInput(),
      'object_name'              => new sfWidgetFormFilterInput(),
      'object_name_indexed'      => new sfWidgetFormFilterInput(),
      'spec_ident_ids'           => new sfWidgetFormFilterInput(),
      'spec_coll_ids'            => new sfWidgetFormFilterInput(),
      'spec_don_sel_ids'         => new sfWidgetFormFilterInput(),
      'collection_type'          => new sfWidgetFormFilterInput(),
      'collection_code'          => new sfWidgetFormFilterInput(),
      'collection_name'          => new sfWidgetFormFilterInput(),
      'collection_is_public'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'collection_parent_ref'    => new sfWidgetFormFilterInput(),
      'collection_path'          => new sfWidgetFormFilterInput(),
      'expedition_name'          => new sfWidgetFormFilterInput(),
      'expedition_name_indexed'  => new sfWidgetFormFilterInput(),
      'gtu_code'                 => new sfWidgetFormFilterInput(),
      'gtu_from_date_mask'       => new sfWidgetFormFilterInput(),
      'gtu_from_date'            => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'gtu_to_date_mask'         => new sfWidgetFormFilterInput(),
      'gtu_to_date'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'gtu_tag_values_indexed'   => new sfWidgetFormFilterInput(),
      'gtu_country_tag_value'    => new sfWidgetFormFilterInput(),
      'gtu_country_tag_indexed'  => new sfWidgetFormFilterInput(),
      'gtu_province_tag_value'   => new sfWidgetFormFilterInput(),
      'gtu_province_tag_indexed' => new sfWidgetFormFilterInput(),
      'gtu_others_tag_value'     => new sfWidgetFormFilterInput(),
      'gtu_others_tag_indexed'   => new sfWidgetFormFilterInput(),
      'gtu_elevation'            => new sfWidgetFormFilterInput(),
      'gtu_elevation_accuracy'   => new sfWidgetFormFilterInput(),
      'taxon_name'               => new sfWidgetFormFilterInput(),
      'taxon_name_indexed'       => new sfWidgetFormFilterInput(),
      'taxon_level_ref'          => new sfWidgetFormFilterInput(),
      'taxon_level_name'         => new sfWidgetFormFilterInput(),
      'taxon_status'             => new sfWidgetFormFilterInput(),
      'taxon_path'               => new sfWidgetFormFilterInput(),
      'taxon_parent_ref'         => new sfWidgetFormFilterInput(),
      'taxon_extinct'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'litho_name'               => new sfWidgetFormFilterInput(),
      'litho_name_indexed'       => new sfWidgetFormFilterInput(),
      'litho_level_ref'          => new sfWidgetFormFilterInput(),
      'litho_level_name'         => new sfWidgetFormFilterInput(),
      'litho_status'             => new sfWidgetFormFilterInput(),
      'litho_local'              => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'litho_color'              => new sfWidgetFormFilterInput(),
      'litho_path'               => new sfWidgetFormFilterInput(),
      'litho_parent_ref'         => new sfWidgetFormFilterInput(),
      'chrono_name'              => new sfWidgetFormFilterInput(),
      'chrono_name_indexed'      => new sfWidgetFormFilterInput(),
      'chrono_level_ref'         => new sfWidgetFormFilterInput(),
      'chrono_level_name'        => new sfWidgetFormFilterInput(),
      'chrono_status'            => new sfWidgetFormFilterInput(),
      'chrono_local'             => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'chrono_color'             => new sfWidgetFormFilterInput(),
      'chrono_path'              => new sfWidgetFormFilterInput(),
      'chrono_parent_ref'        => new sfWidgetFormFilterInput(),
      'lithology_name'           => new sfWidgetFormFilterInput(),
      'lithology_name_indexed'   => new sfWidgetFormFilterInput(),
      'lithology_level_ref'      => new sfWidgetFormFilterInput(),
      'lithology_level_name'     => new sfWidgetFormFilterInput(),
      'lithology_status'         => new sfWidgetFormFilterInput(),
      'lithology_local'          => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'lithology_color'          => new sfWidgetFormFilterInput(),
      'lithology_path'           => new sfWidgetFormFilterInput(),
      'lithology_parent_ref'     => new sfWidgetFormFilterInput(),
      'mineral_name'             => new sfWidgetFormFilterInput(),
      'mineral_name_indexed'     => new sfWidgetFormFilterInput(),
      'mineral_level_ref'        => new sfWidgetFormFilterInput(),
      'mineral_level_name'       => new sfWidgetFormFilterInput(),
      'mineral_status'           => new sfWidgetFormFilterInput(),
      'mineral_local'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'mineral_color'            => new sfWidgetFormFilterInput(),
      'mineral_path'             => new sfWidgetFormFilterInput(),
      'mineral_parent_ref'       => new sfWidgetFormFilterInput(),
      'ig_num'                   => new sfWidgetFormFilterInput(),
      'ig_num_indexed'           => new sfWidgetFormFilterInput(),
      'ig_date_mask'             => new sfWidgetFormFilterInput(),
      'ig_date'                  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'col'                      => new sfWidgetFormFilterInput(),
      'gtu_location'             => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'id'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'category'                 => new sfValidatorPass(array('required' => false)),
      'collection_ref'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'expedition_ref'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gtu_ref'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'taxon_ref'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'litho_ref'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chrono_ref'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lithology_ref'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mineral_ref'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'acquisition_category'     => new sfValidatorPass(array('required' => false)),
      'acquisition_date_mask'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'acquisition_date'         => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'station_visible'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'ig_ref'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'type'                     => new sfValidatorPass(array('required' => false)),
      'type_group'               => new sfValidatorPass(array('required' => false)),
      'type_search'              => new sfValidatorPass(array('required' => false)),
      'sex'                      => new sfValidatorPass(array('required' => false)),
      'stage'                    => new sfValidatorPass(array('required' => false)),
      'state'                    => new sfValidatorPass(array('required' => false)),
      'social_status'            => new sfValidatorPass(array('required' => false)),
      'rock_form'                => new sfValidatorPass(array('required' => false)),
      'specimen_part'            => new sfValidatorPass(array('required' => false)),
      'complete'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'institution_ref'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'building'                 => new sfValidatorPass(array('required' => false)),
      'floor'                    => new sfValidatorPass(array('required' => false)),
      'room'                     => new sfValidatorPass(array('required' => false)),
      'row'                      => new sfValidatorPass(array('required' => false)),
      'shelf'                    => new sfValidatorPass(array('required' => false)),
      'container'                => new sfValidatorPass(array('required' => false)),
      'sub_container'            => new sfValidatorPass(array('required' => false)),
      'container_type'           => new sfValidatorPass(array('required' => false)),
      'sub_container_type'       => new sfValidatorPass(array('required' => false)),
      'container_storage'        => new sfValidatorPass(array('required' => false)),
      'sub_container_storage'    => new sfValidatorPass(array('required' => false)),
      'surnumerary'              => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'specimen_status'          => new sfValidatorPass(array('required' => false)),
      'specimen_count_min'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'specimen_count_max'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'object_name'              => new sfValidatorPass(array('required' => false)),
      'object_name_indexed'      => new sfValidatorPass(array('required' => false)),
      'spec_ident_ids'           => new sfValidatorPass(array('required' => false)),
      'spec_coll_ids'            => new sfValidatorPass(array('required' => false)),
      'spec_don_sel_ids'         => new sfValidatorPass(array('required' => false)),
      'collection_type'          => new sfValidatorPass(array('required' => false)),
      'collection_code'          => new sfValidatorPass(array('required' => false)),
      'collection_name'          => new sfValidatorPass(array('required' => false)),
      'collection_is_public'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'collection_parent_ref'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'collection_path'          => new sfValidatorPass(array('required' => false)),
      'expedition_name'          => new sfValidatorPass(array('required' => false)),
      'expedition_name_indexed'  => new sfValidatorPass(array('required' => false)),
      'gtu_code'                 => new sfValidatorPass(array('required' => false)),
      'gtu_from_date_mask'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gtu_from_date'            => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'gtu_to_date_mask'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gtu_to_date'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'gtu_tag_values_indexed'   => new sfValidatorPass(array('required' => false)),
      'gtu_country_tag_value'    => new sfValidatorPass(array('required' => false)),
      'gtu_country_tag_indexed'  => new sfValidatorPass(array('required' => false)),
      'gtu_province_tag_value'   => new sfValidatorPass(array('required' => false)),
      'gtu_province_tag_indexed' => new sfValidatorPass(array('required' => false)),
      'gtu_others_tag_value'     => new sfValidatorPass(array('required' => false)),
      'gtu_others_tag_indexed'   => new sfValidatorPass(array('required' => false)),
      'gtu_elevation'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'gtu_elevation_accuracy'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'taxon_name'               => new sfValidatorPass(array('required' => false)),
      'taxon_name_indexed'       => new sfValidatorPass(array('required' => false)),
      'taxon_level_ref'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'taxon_level_name'         => new sfValidatorPass(array('required' => false)),
      'taxon_status'             => new sfValidatorPass(array('required' => false)),
      'taxon_path'               => new sfValidatorPass(array('required' => false)),
      'taxon_parent_ref'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'taxon_extinct'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'litho_name'               => new sfValidatorPass(array('required' => false)),
      'litho_name_indexed'       => new sfValidatorPass(array('required' => false)),
      'litho_level_ref'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'litho_level_name'         => new sfValidatorPass(array('required' => false)),
      'litho_status'             => new sfValidatorPass(array('required' => false)),
      'litho_local'              => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'litho_color'              => new sfValidatorPass(array('required' => false)),
      'litho_path'               => new sfValidatorPass(array('required' => false)),
      'litho_parent_ref'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chrono_name'              => new sfValidatorPass(array('required' => false)),
      'chrono_name_indexed'      => new sfValidatorPass(array('required' => false)),
      'chrono_level_ref'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chrono_level_name'        => new sfValidatorPass(array('required' => false)),
      'chrono_status'            => new sfValidatorPass(array('required' => false)),
      'chrono_local'             => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'chrono_color'             => new sfValidatorPass(array('required' => false)),
      'chrono_path'              => new sfValidatorPass(array('required' => false)),
      'chrono_parent_ref'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lithology_name'           => new sfValidatorPass(array('required' => false)),
      'lithology_name_indexed'   => new sfValidatorPass(array('required' => false)),
      'lithology_level_ref'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lithology_level_name'     => new sfValidatorPass(array('required' => false)),
      'lithology_status'         => new sfValidatorPass(array('required' => false)),
      'lithology_local'          => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'lithology_color'          => new sfValidatorPass(array('required' => false)),
      'lithology_path'           => new sfValidatorPass(array('required' => false)),
      'lithology_parent_ref'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mineral_name'             => new sfValidatorPass(array('required' => false)),
      'mineral_name_indexed'     => new sfValidatorPass(array('required' => false)),
      'mineral_level_ref'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mineral_level_name'       => new sfValidatorPass(array('required' => false)),
      'mineral_status'           => new sfValidatorPass(array('required' => false)),
      'mineral_local'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'mineral_color'            => new sfValidatorPass(array('required' => false)),
      'mineral_path'             => new sfValidatorPass(array('required' => false)),
      'mineral_parent_ref'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ig_num'                   => new sfValidatorPass(array('required' => false)),
      'ig_num_indexed'           => new sfValidatorPass(array('required' => false)),
      'ig_date_mask'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ig_date'                  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'col'                      => new sfValidatorPass(array('required' => false)),
      'gtu_location'             => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('zzz_rotifer_specimens_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'ZzzRotiferSpecimens';
  }

  public function getFields()
  {
    return array(
      'id'                       => 'Number',
      'category'                 => 'Text',
      'collection_ref'           => 'Number',
      'expedition_ref'           => 'Number',
      'gtu_ref'                  => 'Number',
      'taxon_ref'                => 'Number',
      'litho_ref'                => 'Number',
      'chrono_ref'               => 'Number',
      'lithology_ref'            => 'Number',
      'mineral_ref'              => 'Number',
      'acquisition_category'     => 'Text',
      'acquisition_date_mask'    => 'Number',
      'acquisition_date'         => 'Date',
      'station_visible'          => 'Boolean',
      'ig_ref'                   => 'Number',
      'type'                     => 'Text',
      'type_group'               => 'Text',
      'type_search'              => 'Text',
      'sex'                      => 'Text',
      'stage'                    => 'Text',
      'state'                    => 'Text',
      'social_status'            => 'Text',
      'rock_form'                => 'Text',
      'specimen_part'            => 'Text',
      'complete'                 => 'Boolean',
      'institution_ref'          => 'Number',
      'building'                 => 'Text',
      'floor'                    => 'Text',
      'room'                     => 'Text',
      'row'                      => 'Text',
      'shelf'                    => 'Text',
      'container'                => 'Text',
      'sub_container'            => 'Text',
      'container_type'           => 'Text',
      'sub_container_type'       => 'Text',
      'container_storage'        => 'Text',
      'sub_container_storage'    => 'Text',
      'surnumerary'              => 'Boolean',
      'specimen_status'          => 'Text',
      'specimen_count_min'       => 'Number',
      'specimen_count_max'       => 'Number',
      'object_name'              => 'Text',
      'object_name_indexed'      => 'Text',
      'spec_ident_ids'           => 'Text',
      'spec_coll_ids'            => 'Text',
      'spec_don_sel_ids'         => 'Text',
      'collection_type'          => 'Text',
      'collection_code'          => 'Text',
      'collection_name'          => 'Text',
      'collection_is_public'     => 'Boolean',
      'collection_parent_ref'    => 'Number',
      'collection_path'          => 'Text',
      'expedition_name'          => 'Text',
      'expedition_name_indexed'  => 'Text',
      'gtu_code'                 => 'Text',
      'gtu_from_date_mask'       => 'Number',
      'gtu_from_date'            => 'Date',
      'gtu_to_date_mask'         => 'Number',
      'gtu_to_date'              => 'Date',
      'gtu_tag_values_indexed'   => 'Text',
      'gtu_country_tag_value'    => 'Text',
      'gtu_country_tag_indexed'  => 'Text',
      'gtu_province_tag_value'   => 'Text',
      'gtu_province_tag_indexed' => 'Text',
      'gtu_others_tag_value'     => 'Text',
      'gtu_others_tag_indexed'   => 'Text',
      'gtu_elevation'            => 'Number',
      'gtu_elevation_accuracy'   => 'Number',
      'taxon_name'               => 'Text',
      'taxon_name_indexed'       => 'Text',
      'taxon_level_ref'          => 'Number',
      'taxon_level_name'         => 'Text',
      'taxon_status'             => 'Text',
      'taxon_path'               => 'Text',
      'taxon_parent_ref'         => 'Number',
      'taxon_extinct'            => 'Boolean',
      'litho_name'               => 'Text',
      'litho_name_indexed'       => 'Text',
      'litho_level_ref'          => 'Number',
      'litho_level_name'         => 'Text',
      'litho_status'             => 'Text',
      'litho_local'              => 'Boolean',
      'litho_color'              => 'Text',
      'litho_path'               => 'Text',
      'litho_parent_ref'         => 'Number',
      'chrono_name'              => 'Text',
      'chrono_name_indexed'      => 'Text',
      'chrono_level_ref'         => 'Number',
      'chrono_level_name'        => 'Text',
      'chrono_status'            => 'Text',
      'chrono_local'             => 'Boolean',
      'chrono_color'             => 'Text',
      'chrono_path'              => 'Text',
      'chrono_parent_ref'        => 'Number',
      'lithology_name'           => 'Text',
      'lithology_name_indexed'   => 'Text',
      'lithology_level_ref'      => 'Number',
      'lithology_level_name'     => 'Text',
      'lithology_status'         => 'Text',
      'lithology_local'          => 'Boolean',
      'lithology_color'          => 'Text',
      'lithology_path'           => 'Text',
      'lithology_parent_ref'     => 'Number',
      'mineral_name'             => 'Text',
      'mineral_name_indexed'     => 'Text',
      'mineral_level_ref'        => 'Number',
      'mineral_level_name'       => 'Text',
      'mineral_status'           => 'Text',
      'mineral_local'            => 'Boolean',
      'mineral_color'            => 'Text',
      'mineral_path'             => 'Text',
      'mineral_parent_ref'       => 'Number',
      'ig_num'                   => 'Text',
      'ig_num_indexed'           => 'Text',
      'ig_date_mask'             => 'Number',
      'ig_date'                  => 'Date',
      'col'                      => 'Text',
      'gtu_location'             => 'Text',
    );
  }
}
