<?php

/**
 * LoanHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoanHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoanHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoanHistory');
    }
}