<?php

/**
 * SpecimensMaincodesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecimensMaincodesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecimensMaincodesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpecimensMaincodes');
    }
}