<?php

/**
 * TvReportingCountAllSpecimensByCollectionYearIgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TvReportingCountAllSpecimensByCollectionYearIgTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TvReportingCountAllSpecimensByCollectionYearIgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TvReportingCountAllSpecimensByCollectionYearIg');
    }
}