<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/12/19 11:12:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=darwin2',
  'username' => 'darwin2',
  'password' => 'darwin123',
  'name' => 'doctrine',
)),);
