<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/14 16:30:35
sfConfig::add(array(
  'tpl_authorizedversion' => array (
  'taxonomy' => 
  array (
    0 => 1.2,
    1 => 1.3,
  ),
  'specimens' => 
  array (
    0 => 1.3999999999999999,
  ),
),
));
