<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/21 13:43:11
sfConfig::add(array(
  'mod_specimensearchwidget_enabled' => true,
  'mod_specimensearchwidget_view_class' => 'sfPHP',
));
