<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/08 16:05:31
sfConfig::add(array(
  'mod_expeditionsigs_enabled' => true,
  'mod_expeditionsigs_view_class' => 'sfPHP',
));
