<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/05 11:05:31
sfConfig::add(array(
  'mod_specimensearch_enabled' => true,
  'mod_specimensearch_view_class' => 'sfPHP',
));
