<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/11/29 08:36:49
$this->security = array (
  'logout' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'lostpwd' => 
  array (
    'is_secure' => false,
  ),
  'pwdrenewmail' => 
  array (
    'is_secure' => false,
  ),
  'renewpwd' => 
  array (
    'is_secure' => false,
  ),
  'lang' => 
  array (
    'is_secure' => false,
  ),
  'submit' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
