<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/30 14:04:47
sfConfig::add(array(
  'mod_loanitemwidget_enabled' => true,
  'mod_loanitemwidget_view_class' => 'sfPHP',
));
