<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/28 10:15:27
sfConfig::add(array(
  'mod_cataloguewidgetview_enabled' => true,
  'mod_cataloguewidgetview_view_class' => 'sfPHP',
));
