<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/30 11:21:13
sfConfig::add(array(
  'mod_cataloguewidget_enabled' => true,
  'mod_cataloguewidget_view_class' => 'sfPHP',
));
