<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/14 16:33:01
sfConfig::add(array(
  'mod_specimenwidget_enabled' => true,
  'mod_specimenwidget_view_class' => 'sfPHP',
));
