<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/30 14:06:38
sfConfig::add(array(
  'mod_loanitemwidgetview_enabled' => true,
  'mod_loanitemwidgetview_view_class' => 'sfPHP',
));
