<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/30 11:20:52
sfConfig::add(array(
  'mod_informativeworkflow_enabled' => true,
  'mod_informativeworkflow_view_class' => 'sfPHP',
));
