<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/30 11:30:56
sfConfig::add(array(
  'mod_cataloguewidgetview_enabled' => true,
  'mod_cataloguewidgetview_view_class' => 'sfPHP',
));
