<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/07/05 12:03:27
sfConfig::add(array(
  'mod_cataloguewidget_enabled' => true,
  'mod_cataloguewidget_view_class' => 'sfPHP',
));
