<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionsTable extends DarwinTable
{
 //note level not used
  public function completeAsArray($user, $needle, $exact, $limit = 30, $level=-1)
  {
    $conn_MGR = Doctrine_Manager::connection();
    $q = Doctrine_Query::create()
      ->from('Collections col')
      ->orderBy('name ASC')
      ;
    if($exact)
      $q->andWhere("name = ?",$needle);
    else
      $q->andWhere("name_indexed like concat('%',fulltoindex(".$conn_MGR->quote($needle, 'string')."),'%') ");

    if($user && ! $user->isA(Users::ADMIN) ) {
      $q->leftJoin('col.CollectionsRights r ON col.id=r.collection_ref AND r.user_ref = '.$user->getId())
        ->andWhere('r.id is not null OR col.is_public = TRUE');

      $q->andWhere('r.db_user_type >= ?',USERS::ENCODER);
    }
    $q_results = $q->execute();
    $result = array();
    foreach($q_results as $item) {
      $result[] = array('label' => $item->getName(), 'name_indexed'=> $item->getNameIndexed(), 'value'=> $item->getId() );
    }
    return $result;
  }

  public function fetchByInstitutionList($user, $institutionId = null, $public_only = false, $only_encodable = false)
  {
    $q = Doctrine_Query::create()
      ->select('p.*, col.*,r.id,r.db_user_type, CONCAT(col.path,col.id,E\'/\') as col_path_id,  regexp_split_to_array(CONCAT(col.path,col.id,E\'/\'), E\'/\') as col_path_id2')
      ->from('People p')
      ->innerJoin('p.Collections col')
      ->andWhere('p.is_physical = false')
      ->orderBy('p.id ASC, col_path_id2 ASC, col.name ASC');


    if($user && ! $user->isA(Users::ADMIN) ) {
      $q->leftJoin('col.CollectionsRights r ON col.id=r.collection_ref AND r.user_ref = '.$user->getId())
        ->andWhere('r.id is not null OR col.is_public = TRUE');

      if($only_encodable) {
        $q->andWhere('r.db_user_type >= ?',USERS::ENCODER);
      }

    } elseif(!$user || $user->isA(Users::ADMIN)  ) {
      $q->leftJoin('col.CollectionsRights r ON col.id=r.collection_ref AND r.user_ref = -1');
    }

    if($public_only) {
      $q->andWhere('col.is_public = TRUE');
    }
    if($institutionId !== null) {
      $q->andWhere('p.id = ?', $institutionId);
    }

    return $q->execute();
  }

  public function getDistinctCollectionByInstitution($inst = null)
  {
    $q = Doctrine_Query::create()
      ->select('c.*, CONCAT(c.path,c.id,E\'/\') as col_path_id')
      ->from('Collections c')
      ->orderBy('col_path_id ASC,c.name ASC');
    if($inst !== null) {
      $q->andWhere('c.institution_ref = ?',$inst);
    }

    $res = $q->execute();
    $results = array('' =>'');
    foreach($res as $row)
    {
      $results[$row->getId()] = $row->__toString();
    }
    return $results;
  }

  public function getCollectionByName($name)
  {
    $q = Doctrine_Query::create()
      ->from('collections c')
      ->where('c.name = ?', $name)
      ->orderBy('c.code ASC');

    return $q->fetchOne();
  }

  public function fetchByCollectionParent($current_user, $user_id, $collection_id)
  {
    $expr = "%/$collection_id/%" ;
    $q = Doctrine_Query::create()
      ->select('c.*, r.*, CONCAT(c.path,c.id,E\'/\') as coll_path_id')
      ->from('Collections c')
      ->leftJoin('c.CollectionsRights r ON c.id=r.collection_ref AND r.user_ref = '.$user_id);
    if(! $current_user->isAtLeast(Users::ADMIN))
      $q->innerJoin('c.CollectionsRights r2 ON c.id=r2.collection_ref AND r2.db_user_type >=4 AND r2.user_ref = '.$current_user->getId());

    $q->andWhere('c.path like ?', $expr)
      ->orderBy('coll_path_id ASC');
    return $q->execute();
  }

  public function getAllCollections($public_only = false)
  {
    $q = Doctrine_Query::create()
      ->from('Collections c')
      ->orderBy('path,name ASC');
    if($public_only)
      $q->andWhere('c.is_public = TRUE');
    return $q->execute();
  }

  public function getAndUpdateLastCode($collectionId)
  {
    if (!isset($collectionId))
      return 0;
    $conn = Doctrine_Manager::connection();
    $collId = $conn->quote($collectionId, 'integer');
    $sql = "UPDATE collections SET code_last_value = code_last_value+1 WHERE id = $collId RETURNING code_last_value";
    $returnedVal = $conn->fetchOne($sql);
    return $returnedVal;
  }

  public function getInstitutionNameByCollection($collection_ref)
  {
    $q = Doctrine_Query::create()
      ->select('p.*')
      ->from('People p')
      ->innerJoin('p.Collections col')
      ->where('col.id = ?', $collection_ref);
    return $q->fetchOne();
  }

  public function getAllAvailableCollectionsFor($user)
  {
    $user_id = $user->getId();
    $q = Doctrine_Query::create()
      ->select('c.*')
      ->from('Collections c')  ;   
    if(!($user->isA(Users::ADMIN)))
      $q->leftJoin('c.CollectionsRights r')
        ->addwhere('r.user_ref = ?',$user_id)
        ->addwhere('db_user_type > 1');
    $q->orderBy('name ASC');
    $res = $q->execute();
    $results = array(0 =>'All');
    foreach($res as $row)
    {
      $results[$row->getId()] = $row->getName();
    }
    return $results;
  }

  public function afterSaveAddCode($collectionId,$specimenId) 
  {
    if (
      $collectionId !== null &&
      $collectionId !== '' &&
      $specimenId !== null &&
      $specimenId !== ''
    ) {
      $conn = Doctrine_Manager::connection();
      $conn->quote($collectionId, 'integer');
      $conn->quote($specimenId, 'integer');
      $conn->getDbh()->exec('BEGIN TRANSACTION;');
      $conn->getDbh()->exec("SELECT fct_after_save_add_code($collectionId, $specimenId)");
      $conn->getDbh()->exec('COMMIT;');
    }
    return 0;
  }
  
    //ftheeten 2018 04 27
  
  
  public function countSpecimens($collectionID ="/", $year="", $creation_date_min="", $creation_date_max="",$collecting_date_min="", $collecting_date_max="",  $ig_num="", $includeSubcollection=false, $detailSubCollections=false ,  $parent_only=false,$hide_private=false, $user=null)
  {
  
    $fields =Array();
    $groups =Array();
    $where =Array();
    $orders=Array();

   
    if(strlen($year)>0)
    {
        $fields[2]="year";
        $where[]= "year = :year";
        $groups[]="year";
    }
    
    if(strlen($creation_date_min)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') >= date_trunc('day',:creation_date_min::timestamp with time zone)";
        $groups[]="year";
    }
    
    if(strlen($creation_date_max)>0)
    {
        $orders[]="year";
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') <= (date_trunc('day',:creation_date_max::timestamp with time zone)  + (24*60*60 - 1) * interval '1 second')";
        $groups[]="year";
    }
    
     if(strlen($ig_num)>0)
    {
         $orders[]="ig_num";
        $fields[3]="ig_num";
         $groups[]="ig_num";
        $where[]= "ig_num = :ig_num";
    }
    
    
    $fields[4]="SUM(nb_records) as nb_database_records";
    $fields[5]="SUM(specimen_count_min) as nb_physical_specimens_low";
    $fields[6]="SUM(specimen_count_max) as nb_physical_specimens_high";
    
	
	if(strlen($collecting_date_min)>0)
    {
		//$orders[]="collecting_year";
        //$fields[7]="collecting_year";
        $where[]= "gtu_from_date >= :collecting_date_min::timestamp";
        //$groups[]="collecting_year";
    }
	
	if(strlen($collecting_date_max)>0)
    {
		//$orders[]="collecting_year";
        //$fields[8]="collecting_year";
        $where[]= "gtu_from_date <= :collecting_date_max::timestamp";
        //$groups[]="collecting_year";
    }
	
	
    if($detailSubCollections)
    {
        $orders[]="collection_path_text";
        $fields[1]="collection_path_text collection_name";
        $groups[]="collection_path_text";
        $includeSubcollection=true;
		$orders[]="collection_ref";
		$fields[]="collection_ref";
		$groups[]="collection_ref";
	
    }
	if($detailSubCollections)
	{
		$fields[]="grscicoll_code";
		$groups[]="grscicoll_code";
	}

    if($includeSubcollection||$collectionID=="/")
    {
        
        if($collectionID=="/")
        {
            $where[]= "collection_path LIKE  :id||'%'";            
        }
		elseif(strpos($collectionID, ","))
		{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "collection_path||'/'||v_reporting_count_all_specimens_by_collection_year_ig.collection_ref||'/' LIKE '%/$tmp_id/%'";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
        else
        {
            //$where[]= "collections.id::varchar  = :ida";
            $where[]= "collection_path||'/'||v_reporting_count_all_specimens_by_collection_year_ig.collection_ref||'/' LIKE '%/'||:idb||'/%'";
        }       
    }
	elseif(strpos($collectionID, ","))
	{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "v_reporting_count_all_specimens_by_collection_year_ig.collection_ref = $tmp_id";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
    else
    {
         $where[]= "v_reporting_count_all_specimens_by_collection_year_ig.collection_ref::varchar  = :id";
    }
    
    ksort($fields);
    
    
	
   $hide_str="";
   $hide_str_where="";
   $test_user=false;
   $user_role=Users::ANONYMOUS;
   $user_id=null;
   if($user!==null)
   {
	   $test_user=true;
	   $user_role=$user->getDbUserType();
	   $user_id=$user->getId();
   }
   if($hide_private)
   {
	   if($user_role==Users::ADMIN)
	   {
		   $hide_str="";
	   }   
	   elseif(!$test_user||$user_role==Users::ANONYMOUS)
	   {
			$hide_str=" INNER JOIN collections ON v_reporting_count_all_specimens_by_collection_year_ig.collection_ref=collections.id AND is_public=true ";
	   }
	   else
	   {
		   $hide_str="LEFT JOIN collections_rights  ON v_reporting_count_all_specimens_by_collection_year_ig.collection_ref= collections_rights.collection_ref AND user_ref=".$user_id."
					INNER JOIN collections ON v_reporting_count_all_specimens_by_collection_year_ig.collection_ref=collections.id ";
			$where[]="(is_public=true OR db_user_type>= 2)";
	   }
   }
    $regex="";
    if(strpos($collectionID, ","))
	{
			
			$array_col_id=explode(",",$collectionID );
			$regex="path ||id::varchar||'/' as full_path, regexp_replace(path ||id::varchar||'/', '(\/(".implode("|", $array_col_id ).")/\d+\/).*', '\\1') as group_coll ";
			if($detailSubCollection)
			{
				$fields[]="group_coll";
				$groups[]="full_path";
				$groups[]="group_coll";
			}
    }
	elseif($collectionID=="/")
	{
		
		if($detailSubCollections)
			{
				$regex="path ||id::varchar||'/' as full_path,  regexp_replace(path ||id::varchar||'/', '(\/\d+/\d+\/).*', '\\1') as group_coll ";
				$fields[]="group_coll";
				$groups[]="full_path";
				$groups[]="group_coll";
			}
	}
	else
	{
		$regex="path ||id::varchar||'/' as full_path, regexp_replace(path ||id::varchar||'/', '(\/".$collectionID."/\d+\/).*', '\\1') as group_coll ";
		if($detailSubCollection)
			{
				$fields[]="group_coll";
				$groups[]="full_path";
				$groups[]="group_coll";
			}
	}
	if(strlen($regex)>0)
	{
		$regex=",".$regex;
	}
	
	$all_fields=implode(", ", $fields);
    $sql ="
	 WITH a AS (SELECT id, REPLACE(name_full_path,'|', '/') collection_path_text, grscicoll_code ".$regex." FROM v_collections_full_path_recursive_grscicoll)  , b as (
	SELECT ".$all_fields." FROM v_reporting_count_all_specimens_by_collection_year_ig INNER JOIN a ON v_reporting_count_all_specimens_by_collection_year_ig.collection_ref=a.id ".$hide_str." WHERE ".implode(" AND ", $where);
    
    if(count($groups)>0)
    {
        $sql = $sql." GROUP BY ".implode(", ", $groups);
    }
    
     if(count($orders)>0)
    {
        $sql = $sql." ORDER BY ".implode(", ", $orders);
    }
    
    $conn = Doctrine_Manager::connection();
	$sql=$sql.")";
	
	if($parent_only && $detailSubCollections)
	{
		$sql=$sql.", c as(
		 SELECT 
		 group_coll, sum(nb_database_records) nb_database_records,sum(nb_physical_specimens_low) nb_physical_specimens_low, sum(nb_physical_specimens_high) nb_physical_specimens_high
		 FROM b group by group_coll
			 )
			 select a.collection_path_text,grscicoll_code, nb_database_records, nb_physical_specimens_low, nb_physical_specimens_high from c left join a on c.group_coll=a.full_path ORDER BY collection_path_text";
	}
	else
	{
		$sql=$sql."SELECT * FROM b";
	}
	
    $q = $conn->prepare($sql);
    
     if(strlen($year)>0)
    {
        $q->bindParam(":year", $year);
    }
    
     if(strlen($ig_num)>0)
    {
       $q->bindParam(":ig_num", $ig_num, PDO::PARAM_STR);
    }
    
    if($includeSubcollection||$collectionID=="/")    
    {
        
        if($collectionID=="/")
        {
            $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
            
        }
        elseif(strpos($collectionID,"," )===FALSE)
        {
            //$q->bindParam(":ida", $collectionID, PDO::PARAM_STR);
            $q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
        }       
    }
    elseif(strpos($collectionID,"," )===FALSE)
    {
         $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_min)>0)
    {
         $q->bindParam(":creation_date_min", $creation_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_max)>0)
    {
        $q->bindParam(":creation_date_max", $creation_date_max, PDO::PARAM_STR);
    }
       
   
    if(strlen($collecting_date_min)>0)
    {
         $q->bindParam(":collecting_date_min", $collecting_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($collecting_date_max)>0)
    {
        $q->bindParam(":collecting_date_max", $collecting_date_max, PDO::PARAM_STR);
    }


    $q->execute();
    
    $items=$q->fetchAll(PDO::FETCH_ASSOC);

    return $items;
  }
  
    public function countTypeSpecimens($collectionID ="/", $year="", $creation_date_min="", $creation_date_max="",$collecting_date_min="", $collecting_date_max="", $ig_num="", $includeSubcollection=false, $detailSubCollections=false ,  $parent_only=false,$hide_private=false,$user=null )
  {
  
    $fields =Array();
    $groups =Array();
    $where =Array();
    $orders=Array();
    /*if($detailSubCollection>0)
    {
        $fields[0]="collection_name";
        $fields[1]="type";
        $groups[]="collection_name";
        $groups[]="type";
        
    */
   
    if(strlen($year)>0)
    {
        $fields[2]="year";
        $where[]= "year = :year";
        $groups[]="year";
    }
    
    if(strlen($creation_date_min)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') >= (date_trunc('day',:creation_date_min::timestamp with time zone))";
        $groups[]="year";
		 $orders[]="year";
    }
    
    if(strlen($creation_date_max)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') <= (date_trunc('day',:creation_date_max::timestamp with time zone)  + (24*60*60 - 1) * interval '1 second')";
        $groups[]="year";
		 $orders[]="year";
    }
    
     if(strlen($ig_num)>0)
    {
        $fields[3]="ig_num";
         $groups[]="ig_num";
        $where[]= "ig_num = :ig_num";
    }
    
    
    $fields[4]="SUM(nb_records) as nb_database_records";
    $fields[5]="SUM(specimen_count_min) as nb_physical_specimens_low";
    $fields[6]="SUM(specimen_count_max) as nb_physical_specimens_high";
	
	if(strlen($collecting_date_min)>0)
    {
		//$orders[]="collecting_year";
        //$fields[7]="collecting_year";
        $where[]= "gtu_from_date >= :collecting_date_min::timestamp";
        //$groups[]="collecting_year";
    }
	
	if(strlen($collecting_date_max)>0)
    {
		//$orders[]="collecting_year";
        //$fields[8]="collecting_year";
        $where[]= "gtu_from_date <= :collecting_date_max::timestamp";
        //$groups[]="collecting_year";
    }
    
    $orders[]="type";
    $fields[1]="type";
    $groups[]="type";
    
    if($detailSubCollections)
    {
        
        $orders[]="collection_name";
        $fields[0]="collection_name";
        
        $groups[]="collection_name";
        $includeSubcollection=true;
    }
    
    if($includeSubcollection||$collectionID=="/")
    {
        
        if($collectionID=="/")
        {
            $where[]= "collection_path LIKE  :id||'%'";            
        }
		elseif(strpos($collectionID, ","))
		{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "collection_path||'/'||v_reporting_count_all_specimens_type_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/$tmp_id/%'";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
        else
        {
            //$where[]= "collections.id::varchar  = :ida";
            $where[]= "collection_path||'/'||v_reporting_count_all_specimens_type_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/'||:idb||'/%'";
        }       
    }
	elseif(strpos($collectionID, ","))
	{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "v_reporting_count_all_specimens_type_by_collection_ref_year_ig.collection_ref = $tmp_id";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
    else
    {
         $where[]= "v_reporting_count_all_specimens_type_by_collection_ref_year_ig.collection_ref::varchar  = :id";
    }
    
    $where[]="type <> 'specimen'";
    $where[]="type <> 'specimens'";
    $where[]="type IS NOT NULL";
    $where[]="type <> ''";
    
    ksort($fields);
    if($detailSubCollections)
	{
		$fields[]="grscicoll_code";
		$groups[]="grscicoll_code";
	}
   
   
   $hide_str="";
   if($user!==null)
   {
	   $test_user=true;
	   $user_role=$user->getDbUserType();
	   $user_id=$user->getId();
   }
   if($hide_private)
   {
	   
	   if($user_role==Users::ADMIN)
	   {
		   $hide_str="";
	   }   
	   elseif(!$test_user||$user_role==Users::ANONYMOUS)
	   {
			$hide_str=" INNER JOIN collections ON v_reporting_count_all_specimens_type_by_collection_ref_year_ig.collection_ref=collections.id AND is_public=true ";
	   }
	   else
	   {
		   $hide_str="LEFT JOIN collections_rights  ON v_reporting_count_all_specimens_type_by_collection_ref_year_ig.collection_ref= collections_rights.collection_ref AND user_ref=".$user_id."
					INNER JOIN collections ON v_reporting_count_all_specimens_type_by_collection_ref_year_ig.collection_ref=collections.id ";
			$where[]="(is_public=true OR db_user_type>= 2)";
	   }
   }
   if(strpos($collectionID, ",")&& $detailSubCollections)
	{
			
			$array_col_id=explode(",",$collectionID );
			$regex="path ||id::varchar||'/' as full_path, regexp_replace(path ||id::varchar||'/', '(\/(".implode("|", $array_col_id ).")/\d+\/).*', '\\1') as group_coll ";
			$fields[]=$regex;
			$groups[]="path";
			$groups[]="id";
			/*$fields[]="group_coll";
			$groups[]="full_path";
			$groups[]="group_coll";*/
    }
	elseif($collectionID=="/"&& $detailSubCollections)
	{
		$regex="path ||id::varchar||'/' as full_path,  regexp_replace(path ||id::varchar||'/', '(\/\d+/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="path";
		$groups[]="id";
		/*$fields[]="group_coll";
		$groups[]="full_path";
		$groups[]="group_coll";*/
	}
	elseif($detailSubCollections)
	{
		$regex="path ||id::varchar||'/' as full_path, regexp_replace(path ||id::varchar||'/', '(\/".$collectionID."/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="path";
		$groups[]="id";
		/*$fields[]="group_coll";
		$groups[]="full_path";
		$groups[]="group_coll";*/
	}
	
    $all_fields=implode(", ", $fields);
	if( $parent_only && $detailSubCollections)
	{
		$tmpsql ="SELECT ".$all_fields." FROM v_collections_full_path_recursive_grscicoll LEFT JOIN v_reporting_count_all_specimens_type_by_collection_ref_year_ig ON v_collections_full_path_recursive_grscicoll.id=collection_ref ".$hide_str."  WHERE ".implode(" AND ", $where);
		if(count($groups)>0)
		{
			$tmpsql = $tmpsql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$tmpsql = $tmpsql." ORDER BY ".implode(", ", $orders);
		}
		$sql="with a as (".$tmpsql.") select 
REPLACE(name_full_path,'|','/')	  collection_path_text,
a.grscicoll_code,
sum(nb_database_records) nb_database_records, 
sum(nb_physical_specimens_low) nb_physical_specimens_low,
sum(nb_physical_specimens_high) nb_physical_specimens_high
from a 
left join v_collections_full_path_recursive_grscicoll b
on b.path||b.id::varchar||'/' = group_coll
group by group_coll, name_full_path, a.grscicoll_code ORDER BY name_full_path;";
	}
	else
	{
		$sql ="SELECT ".$all_fields." FROM v_collections_full_path_recursive_grscicoll LEFT JOIN v_reporting_count_all_specimens_type_by_collection_ref_year_ig ON v_collections_full_path_recursive_grscicoll.id=collection_ref ".$hide_str."  WHERE ".implode(" AND ", $where);
			if(count($groups)>0)
		{
			$sql = $sql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$sql = $sql." ORDER BY ".implode(", ", $orders);
		}
    }
    

    $conn = Doctrine_Manager::connection();
    $q = $conn->prepare($sql);
    
     if(strlen($year)>0)
    {
        $q->bindParam(":year", $year);
    }
    
     if(strlen($ig_num)>0)
    {
       $q->bindParam(":ig_num", $ig_num, PDO::PARAM_STR);
    }
    
    if($includeSubcollection||$collectionID=="/")    
    {
        
        if($collectionID=="/")
        {
            $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
            
        }
        elseif(strpos($collectionID,",")===false)
        {
            //$q->bindParam(":ida", $collectionID, PDO::PARAM_STR);
            $q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
        }       
    }
    elseif(strpos($collectionID,",")===false)
    {
         $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_min)>0)
    {
         $q->bindParam(":creation_date_min", $creation_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_max)>0)
    {
        $q->bindParam(":creation_date_max", $creation_date_max, PDO::PARAM_STR);
    }
       
	if(strlen($collecting_date_min)>0)
    {
         $q->bindParam(":collecting_date_min", $collecting_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($collecting_date_max)>0)
    {
        $q->bindParam(":collecting_date_max", $collecting_date_max, PDO::PARAM_STR);
    }  
   
   
    $q->execute();
    
    $items=$q->fetchAll(PDO::FETCH_ASSOC);

    return $items;
  }
  
  public function countCategoriesInSpecimens($collectionID ="/", $year="", $creation_date_min="", $creation_date_max="", $collecting_date_min="", $collecting_date_max="",$ig_num="", $includeSubcollection=false, $detailSubCollections=false ,  $parent_only=false,$hide_private=false,$user=null )
  {
  
    $fields =Array();
    $groups =Array();
    $where =Array();
    $orders=Array();
  
   
    if(strlen($year)>0)
    {
        $fields[2]="year";
        $where[]= "year = :year";
        $groups[]="year";
    }
    
    if(strlen($creation_date_min)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') >= (date_trunc('day',:creation_date_min::timestamp with time zone))";
        $groups[]="year";
		 $orders[]="year";
    }
    
    if(strlen($creation_date_max)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') <= (date_trunc('day',:creation_date_max::timestamp with time zone)  + (24*60*60 - 1) * interval '1 second')";
        $groups[]="year";
		 $orders[]="year";
    }
    
     if(strlen($ig_num)>0)
    {
        $fields[3]="ig_num";
         $groups[]="ig_num";
        $where[]= "ig_num = :ig_num";
    }
	
	if(strlen($collecting_date_min)>0)
    {
		//$orders[]="collecting_year";
        //$fields[7]="collecting_year";
        $where[]= "gtu_from_date >= :collecting_date_min::timestamp";
        //$groups[]="collecting_year";
    }
	
	if(strlen($collecting_date_max)>0)
    {
		//$orders[]="collecting_year";
        //$fields[8]="collecting_year";
        $where[]= "gtu_from_date <= :collecting_date_max::timestamp";
        //$groups[]="collecting_year";
    }
    
    
    $fields[4]="SUM(nb_records) as nb_database_records";
    $fields[5]="SUM(specimen_count_min) as nb_physical_specimens_low";
    $fields[6]="SUM(specimen_count_max) as nb_physical_specimens_high";
    
    $orders[]="category";
    $fields[1]="category";
    $groups[]="category";
    
    if($detailSubCollections)
    {
        
        $orders[]="collection_name";
        $fields[0]="collection_name";
        
        $groups[]="collection_name";
        $includeSubcollection=true;
    }
    
    if($includeSubcollection||$collectionID=="/")
    {
        
        if($collectionID=="/")
        {
            $where[]= "collection_path LIKE  :id||'%'";            
        }
		elseif(strpos($collectionID, ","))
		{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "collection_path||'/'||v_reporting_count_all_spec_category_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/$tmp_id/%'";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
        else
        {
            //$where[]= "collections.id::varchar  = :ida";
            $where[]= "collection_path||'/'||v_reporting_count_all_spec_category_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/'||:idb||'/%'";
        }       
    }
	elseif(strpos($collectionID, ","))
	{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "v_reporting_count_all_spec_category_by_collection_ref_year_ig.collection_ref = $tmp_id";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
    else
    {
         $where[]= "v_reporting_count_all_spec_category_by_collection_ref_year_ig.collection_ref::varchar  = :id";
    }
    
   
    
    ksort($fields);
    if($detailSubCollections)
	{
		$fields[]="grscicoll_code";
		$groups[]="grscicoll_code";
	}
   
  
   $hide_str="";
   if($user!==null)
   {
	   $test_user=true;
	   $user_role=$user->getDbUserType();
	   $user_id=$user->getId();
   }
   if($hide_private)
   {
	   
	   if($user_role==Users::ADMIN)
	   {
		   $hide_str="";
	   }   
	   elseif(!$test_user||$user_role==Users::ANONYMOUS)
	   {
			$hide_str=" INNER JOIN collections ON v_reporting_count_all_spec_category_by_collection_ref_year_ig.collection_ref=collections.id AND collections.is_public=true ";
	   }
	   else
	   {
		   $hide_str="LEFT JOIN collections_rights  ON v_reporting_count_all_spec_category_by_collection_ref_year_ig.collection_ref= collections_rights.collection_ref AND user_ref=".$user_id."
					INNER JOIN collections ON v_reporting_count_all_spec_category_by_collection_ref_year_ig.collection_ref=collections.id ";
			$where[]="(collections.is_public=true OR db_user_type>= 2)";
	   }
   }
   if(strpos($collectionID, ",")&& $detailSubCollections)
	{
			
			$array_col_id=explode(",",$collectionID );
			$regex="v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/' as full_path, regexp_replace(v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/', '(\/(".implode("|", $array_col_id ).")/\d+\/).*', '\\1') as group_coll ";
			$fields[]=$regex;
			$groups[]="v_collections_full_path_recursive_grscicoll.path";
			$groups[]="v_collections_full_path_recursive_grscicoll.id";
			/*$fields[]="group_coll";
			$groups[]="full_path";
			$groups[]="group_coll";*/
    }
	elseif($collectionID=="/"&& $detailSubCollections)
	{
		$regex="v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/' as full_path,  regexp_replace(v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/', '(\/\d+/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="v_collections_full_path_recursive_grscicoll.path";
		$groups[]="v_collections_full_path_recursive_grscicoll.id";
		/*$fields[]="group_coll";
		$groups[]="full_path";
		$groups[]="group_coll";*/
	}
	elseif($detailSubCollections)
	{
		$regex="v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/' as full_path, regexp_replace(v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/', '(\/".$collectionID."/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="v_collections_full_path_recursive_grscicoll.path";
		$groups[]="v_collections_full_path_recursive_grscicoll.id";
		/*$fields[]="group_coll";
		$groups[]="full_path";
		$groups[]="group_coll";*/
	}
	
    $all_fields=implode(", ", $fields);
	if( $parent_only && $detailSubCollections)
	{
		$tmpsql ="SELECT ".$all_fields." FROM v_collections_full_path_recursive_grscicoll LEFT JOIN v_reporting_count_all_spec_category_by_collection_ref_year_ig ON v_collections_full_path_recursive_grscicoll.id=collection_ref ".$hide_str."  WHERE ".implode(" AND ", $where);
		if(count($groups)>0)
		{
			$tmpsql = $tmpsql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$tmpsql = $tmpsql." ORDER BY ".implode(", ", $orders);
		}
		$sql="with a as (".$tmpsql.") select 
REPLACE(name_full_path,'|','/')	  collection_path_text,
a.grscicoll_code,
category,
sum(nb_database_records) nb_database_records, 
sum(nb_physical_specimens_low) nb_physical_specimens_low,
sum(nb_physical_specimens_high) nb_physical_specimens_high
from a 
left join v_collections_full_path_recursive_grscicoll b
on b.path||b.id::varchar||'/' = group_coll
group by group_coll, name_full_path, a.grscicoll_code, category ORDER BY name_full_path;";
	}
	else
	{
		$sql ="SELECT ".$all_fields." FROM v_collections_full_path_recursive_grscicoll LEFT JOIN v_reporting_count_all_spec_category_by_collection_ref_year_ig ON v_collections_full_path_recursive_grscicoll.id=collection_ref ".$hide_str."  WHERE ".implode(" AND ", $where);
			if(count($groups)>0)
		{
			$sql = $sql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$sql = $sql." ORDER BY ".implode(", ", $orders);
		}
    }


    $conn = Doctrine_Manager::connection();
    $q = $conn->prepare($sql);
    
     if(strlen($year)>0)
    {
        $q->bindParam(":year", $year);
    }
    
     if(strlen($ig_num)>0)
    {
       $q->bindParam(":ig_num", $ig_num, PDO::PARAM_STR);
    }
    
    if($includeSubcollection||$collectionID=="/")    
    {
        
        if($collectionID=="/")
        {
            $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
            
        }
        elseif(strpos($collectionID,",")===false)
        {
            //$q->bindParam(":ida", $collectionID, PDO::PARAM_STR);
            $q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
        }       
    }
    elseif(strpos($collectionID,",")===false)
    {
         $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_min)>0)
    {
         $q->bindParam(":creation_date_min", $creation_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_max)>0)
    {
        $q->bindParam(":creation_date_max", $creation_date_max, PDO::PARAM_STR);
    }
       
	if(strlen($collecting_date_min)>0)
    {
         $q->bindParam(":collecting_date_min", $collecting_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($collecting_date_max)>0)
    {
        $q->bindParam(":collecting_date_max", $collecting_date_max, PDO::PARAM_STR);
    }   
   
   
    $q->execute();

    $items=$q->fetchAll(PDO::FETCH_ASSOC);

    return $items;
  }
  
  
  public function countPartsInSpecimens($collectionID ="/", $year="", $creation_date_min="", $creation_date_max="", $collecting_date_min="", $collecting_date_max="", $ig_num="", $includeSubcollection=false, $detailSubCollections=false ,  $parent_only=false,$hide_private=false,$user=null )
  {
  
    $fields =Array();
    $groups =Array();
    $where =Array();
    $orders=Array();
  
   
    if(strlen($year)>0)
    {
        $fields[2]="year";
        $where[]= "year = :year";
        $groups[]="year";
    }
    
    if(strlen($creation_date_min)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') >= (date_trunc('day',:creation_date_min::timestamp with time zone))";
        $groups[]="year";
		 $orders[]="year";
    }
    
    if(strlen($creation_date_max)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') <= (date_trunc('day',:creation_date_max::timestamp with time zone)  + (24*60*60 - 1) * interval '1 second')";
        $groups[]="year";
		 $orders[]="year";
    }
    
     if(strlen($ig_num)>0)
    {
        $fields[3]="ig_num";
         $groups[]="ig_num";
        $where[]= "ig_num = :ig_num";
    }
    
	
	if(strlen($collecting_date_min)>0)
    {
		//$orders[]="collecting_year";
        //$fields[7]="collecting_year";
        $where[]= "gtu_from_date >= :collecting_date_min::timestamp";
        //$groups[]="collecting_year";
    }
	
	if(strlen($collecting_date_max)>0)
    {
		//$orders[]="collecting_year";
        //$fields[8]="collecting_year";
        $where[]= "gtu_from_date <= :collecting_date_max::timestamp";
        //$groups[]="collecting_year";
    }
	
    
    $fields[4]="SUM(nb_records) as nb_database_records";
    $fields[5]="SUM(specimen_count_min) as nb_physical_specimens_low";
    $fields[6]="SUM(specimen_count_max) as nb_physical_specimens_high";
    
    $orders[]="specimen_part";
    $fields[1]="specimen_part";
    $groups[]="specimen_part";
	
	if(strlen($collecting_date_max)>0)
    {
		//$orders[]="collecting_year";
        //$fields[8]="collecting_year";
        $where[]= "gtu_from_date <= :collecting_date_max::timestamp";
        //$groups[]="collecting_year";
    }
    
    if($detailSubCollections)
    {
        
        $orders[]="collection_name";
        $fields[0]="collection_name";
        
        $groups[]="collection_name";
        $includeSubcollection=true;
    }
    
    if($includeSubcollection||$collectionID=="/")
    {
        
        if($collectionID=="/")
        {
            $where[]= "collection_path LIKE  :id||'%'";            
        }
		elseif(strpos($collectionID, ","))
		{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "collection_path||'/'||v_reporting_count_all_spec_parts_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/$tmp_id/%'";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
        else
        {
            //$where[]= "collections.id::varchar  = :ida";
            $where[]= "collection_path||'/'||v_reporting_count_all_spec_parts_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/'||:idb||'/%'";
        }       
    }
	elseif(strpos($collectionID, ","))
	{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "v_reporting_count_all_spec_parts_by_collection_ref_year_ig.collection_ref = $tmp_id";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
    else
    {
         $where[]= "v_reporting_count_all_spec_parts_by_collection_ref_year_ig.collection_ref::varchar  = :id";
    }
    
   
    
    ksort($fields);
    if($detailSubCollections)
	{
		$fields[]="grscicoll_code";
		$groups[]="grscicoll_code";
	}
   
   
   $hide_str="";
   if($user!==null)
   {
	   $test_user=true;
	   $user_role=$user->getDbUserType();
	   $user_id=$user->getId();
   }
   if($hide_private)
   {
	   
	   if($user_role==Users::ADMIN)
	   {
		   $hide_str="";
	   }   
	   elseif(!$test_user||$user_role==Users::ANONYMOUS)
	   {
			$hide_str=" INNER JOIN collections ON v_reporting_count_all_spec_parts_by_collection_ref_year_ig.collection_ref=collections.id AND collections.is_public=true ";
	   }
	   else
	   {
		   $hide_str="LEFT JOIN collections_rights  ON v_reporting_count_all_spec_parts_by_collection_ref_year_ig.collection_ref= collections_rights.collection_ref AND user_ref=".$user_id."
					INNER JOIN collections ON v_reporting_count_all_spec_parts_by_collection_ref_year_ig.collection_ref=collections.id ";
			$where[]="(collections.is_public=true OR db_user_type>= 2)";
	   }
   }
   if(strpos($collectionID, ",")&& $detailSubCollections)
	{
			
			$array_col_id=explode(",",$collectionID );
			$regex="v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/' as full_path, regexp_replace(v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/', '(\/(".implode("|", $array_col_id ).")/\d+\/).*', '\\1') as group_coll ";
			$fields[]=$regex;
			$groups[]="v_collections_full_path_recursive_grscicoll.path";
			$groups[]="v_collections_full_path_recursive_grscicoll.id";
			
    }
	elseif($collectionID=="/"&& $detailSubCollections)
	{
		$regex="v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/' as full_path,  regexp_replace(v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/', '(\/\d+/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="v_collections_full_path_recursive_grscicoll.path";
		$groups[]="v_collections_full_path_recursive_grscicoll.id";
		
	}
	elseif($detailSubCollections)
	{
		$regex="v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/' as full_path, regexp_replace(v_collections_full_path_recursive_grscicoll.path ||v_collections_full_path_recursive_grscicoll.id::varchar||'/', '(\/".$collectionID."/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="v_collections_full_path_recursive_grscicoll.path";
		$groups[]="v_collections_full_path_recursive_grscicoll.id";
		
	}
	
    $all_fields=implode(", ", $fields);
	if( $parent_only && $detailSubCollections)
	{
		$tmpsql ="SELECT ".$all_fields." FROM v_collections_full_path_recursive_grscicoll LEFT JOIN v_reporting_count_all_spec_parts_by_collection_ref_year_ig ON v_collections_full_path_recursive_grscicoll.id=collection_ref ".$hide_str."  WHERE ".implode(" AND ", $where);
		if(count($groups)>0)
		{
			$tmpsql = $tmpsql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$tmpsql = $tmpsql." ORDER BY ".implode(", ", $orders);
		}
		$sql="with a as (".$tmpsql.") select 
REPLACE(name_full_path,'|','/')	  collection_path_text,
a.grscicoll_code,
sum(nb_database_records) nb_database_records, 
sum(nb_physical_specimens_low) nb_physical_specimens_low,
sum(nb_physical_specimens_high) nb_physical_specimens_high,
specimen_part
FROM a 
LEFT JOIN v_collections_full_path_recursive_grscicoll b
ON b.path||b.id::varchar||'/' = group_coll
GROUP BY group_coll, name_full_path, a.grscicoll_code, specimen_part ORDER BY name_full_path;";
	}
	else
	{
		$sql ="SELECT ".$all_fields." FROM v_collections_full_path_recursive_grscicoll LEFT JOIN v_reporting_count_all_spec_parts_by_collection_ref_year_ig ON v_collections_full_path_recursive_grscicoll.id=collection_ref ".$hide_str."  WHERE ".implode(" AND ", $where);
			if(count($groups)>0)
		{
			$sql = $sql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$sql = $sql." ORDER BY ".implode(", ", $orders);
		}
    }
    

    $conn = Doctrine_Manager::connection();
    $q = $conn->prepare($sql);
    
     if(strlen($year)>0)
    {
        $q->bindParam(":year", $year);
    }
    
     if(strlen($ig_num)>0)
    {
       $q->bindParam(":ig_num", $ig_num, PDO::PARAM_STR);
    }
    
    if($includeSubcollection||$collectionID=="/")    
    {
        
        if($collectionID=="/")
        {
            $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
            
        }
        elseif(strpos($collectionID,",")===false)
        {
            //$q->bindParam(":ida", $collectionID, PDO::PARAM_STR);
            $q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
        }       
    }
    elseif(strpos($collectionID,",")===false)
    {
         $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_min)>0)
    {
         $q->bindParam(":creation_date_min", $creation_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_max)>0)
    {
        $q->bindParam(":creation_date_max", $creation_date_max, PDO::PARAM_STR);
    }
       
	   
	 if(strlen($collecting_date_min)>0)
    {
         $q->bindParam(":collecting_date_min", $collecting_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($collecting_date_max)>0)
    {
        $q->bindParam(":collecting_date_max", $collecting_date_max, PDO::PARAM_STR);
    }

   
   
    $q->execute();

    $items=$q->fetchAll(PDO::FETCH_ASSOC);

    return $items;
  }
  
   public function countMidsSpecimens($collectionID ="/", $year="", $creation_date_min="", $creation_date_max="",$collecting_date_min="", $collecting_date_max="", $ig_num="", $includeSubcollection=false, $detailSubCollections=false , $hide_private=false,$user=null )
  {
  
    $fields =Array();
    $groups =Array();
    $where =Array();
    $orders=Array();
    if($detailSubCollection>0)
    {
        $fields[0]="collection_name";
        $fields[1]="mids_level";
        $groups[]="collection_name";
        $groups[]="mids_level";
        
    }
   
    if(strlen($year)>0)
    {
        $fields[2]="year";
        $where[]= "year = :year";
        $groups[]="year";
    }
    
    if(strlen($creation_date_min)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') >= (date_trunc('day',:creation_date_min::timestamp with time zone))";
        $groups[]="year";
		 $orders[]="year";
    }
    
    if(strlen($creation_date_max)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(specimen_creation_date,'1706-01-01 00:00:00') <= (date_trunc('day',:creation_date_max::timestamp with time zone)  + (24*60*60 - 1) * interval '1 second')";
        $groups[]="year";
		 $orders[]="year";
    }
    
     if(strlen($ig_num)>0)
    {
        $fields[3]="ig_num";
         $groups[]="ig_num";
        $where[]= "ig_num = :ig_num";
    }
    
    
    $fields[4]="SUM(nb_records) as nb_database_records";
	$fields[5]="SUM(specimen_count_min) as nb_physical_specimens_low";
    $fields[6]="SUM(specimen_count_max) as nb_physical_specimens_high";
   
    
    $orders[]="mids_level";
    $fields[1]="mids_level";
    $groups[]="mids_level";
    
	
	if(strlen($collecting_date_min)>0)
    {
		//$orders[]="collecting_year";
        //$fields[7]="collecting_year";
        $where[]= "gtu_from_date >= :collecting_date_min::timestamp";
        //$groups[]="collecting_year";
    }
	
	if(strlen($collecting_date_max)>0)
    {
		//$orders[]="collecting_year";
        //$fields[8]="collecting_year";
        $where[]= "gtu_from_date <= :collecting_date_max::timestamp";
        //$groups[]="collecting_year";
    }
	
	
    if($detailSubCollections)
    {
        
        $orders[]="collection_name";
        $fields[0]="collection_name";
        
        $groups[]="collection_name";
        $includeSubcollection=true;
    }
    
    if($includeSubcollection||$collectionID=="/")
    {
        
        if($collectionID=="/")
        {
            $where[]= "collection_path LIKE  :id||'%'";            
        }
		elseif(strpos($collectionID, ","))
		{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "collection_path||'/'||v_reporting_count_all_specimens_mids_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/$tmp_id/%'";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
        else
        {
            //$where[]= "collections.id::varchar  = :ida";
            $where[]= "collection_path||'/'||v_reporting_count_all_specimens_mids_by_collection_ref_year_ig.collection_ref||'/' LIKE '%/'||:idb||'/%'";
        }       
    }
	elseif(strpos($collectionID, ","))
	{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "v_reporting_count_all_specimens_mids_by_collection_ref_year_ig.collection_ref = $tmp_id";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
    else
    {
         $where[]= "v_reporting_count_all_specimens_mids_by_collection_ref_year_ig.collection_ref::varchar  = :id";
    }
    
   
    
    ksort($fields);
	if($detailSubCollections)
	{
		$fields[]="grscicoll_code";
		$groups[]="grscicoll_code";
    }
    $all_fields=implode(", ", $fields);
   
   $hide_str="";
   if($user!==null)
   {
	   $test_user=true;
	   $user_role=$user->getDbUserType();
	   $user_id=$user->getId();
   }
   if($hide_private)
   {
	   
	   if($user_role==Users::ADMIN)
	   {
		   $hide_str="";
	   }   
	   elseif(!$test_user||$user_role==Users::ANONYMOUS)
	   {
			$hide_str=" INNER JOIN collections ON v_reporting_count_all_specimens_mids_by_collection_ref_year_ig.collection_ref=collections.id AND is_public=true ";
	   }
	   else
	   {
		   $hide_str="LEFT JOIN collections_rights  ON v_reporting_count_all_specimens_mids_by_collection_ref_year_ig.collection_ref= collections_rights.collection_ref AND user_ref=".$user_id."
					INNER JOIN collections ON v_reporting_count_all_specimens_mids_by_collection_ref_year_ig.collection_ref=collections.id ";
			$where[]="(is_public=true OR db_user_type>= 2)";
	   }
   }
    $sql ="SELECT ".$all_fields." FROM v_collections_full_path_recursive_grscicoll LEFT JOIN v_reporting_count_all_specimens_mids_by_collection_ref_year_ig ON v_collections_full_path_recursive_grscicoll.id=collection_ref ".$hide_str."  WHERE ".implode(" AND ", $where);
    
    if(count($groups)>0)
    {
        $sql = $sql." GROUP BY ".implode(", ", $groups);
    }
    
     if(count($orders)>0)
    {
        $sql = $sql." ORDER BY ".implode(", ", $orders);
    }
    
    $conn = Doctrine_Manager::connection();
    $q = $conn->prepare($sql);
    
     if(strlen($year)>0)
    {
        $q->bindParam(":year", $year);
    }
    
     if(strlen($ig_num)>0)
    {
       $q->bindParam(":ig_num", $ig_num, PDO::PARAM_STR);
    }
    
    if($includeSubcollection||$collectionID=="/")    
    {
        
        if($collectionID=="/")
        {
            $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
            
        }
        elseif(strpos($collectionID,",")===false)
        {
            //$q->bindParam(":ida", $collectionID, PDO::PARAM_STR);
            $q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
        }       
    }
    elseif(strpos($collectionID,",")===false)
    {
         $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_min)>0)
    {
         $q->bindParam(":creation_date_min", $creation_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_max)>0)
    {
        $q->bindParam(":creation_date_max", $creation_date_max, PDO::PARAM_STR);
    }
       
   	 if(strlen($collecting_date_min)>0)
    {
         $q->bindParam(":collecting_date_min", $collecting_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($collecting_date_max)>0)
    {
        $q->bindParam(":collecting_date_max", $collecting_date_max, PDO::PARAM_STR);
    }
   
    $q->execute();
    
    $items=$q->fetchAll(PDO::FETCH_ASSOC);

    return $items;
  }
  
   public function countCountriesInSpecimens($collectionID ="/", $year="", $creation_date_min="", $creation_date_max="",$collecting_date_min="", $collecting_date_max="" , $ig_num="", $includeSubcollection=false, $detailSubCollections=false , $hide_private=false,$user=null )
  {
		$fields_agg =Array();
		$fields =Array();
		
		$where_agg =Array();
		$group_agg =Array();
		$where =Array();
		$orders=Array();
		$params=Array();
		$groups =Array();
		
		$agg_table1=" WITH a AS(SELECT id, path||id::varchar||'/' as collection_full_path, collection_type, code, name, name_indexed, code_full_path, name_full_path, name_indexed_full_path,grscicoll_code FROM darwin2.v_collections_full_path_recursive_grscicoll  ), b AS (SELECT INITCAP(regexp_replace(regexp_replace(regexp_replace(trim(gtu_country_tag_value),'\s+', ' ' ,'g') , '\s*;\s*' , ';','g'), ';+',';','g'))  gtu_country_tag_value , type, specimen_count_min,specimen_count_max, collection_full_path, from_date,from_date_mask, ig_num ";
		$agg_table2.=" FROM  specimens INNER JOIN a  ON  specimens.collection_ref=a.id LEFT JOIN temporal_information ON specimens.id=temporal_information.specimen_ref ";
		$agg_table3= ") , c AS (SELECT DISTINCT  gtu_country_tag_value, LOWER(type) as spec_type ";
		$agg_table4= " , COUNT(*) as nb_database_records,
			 sum(specimen_count_min)  nb_physical_specimens_low,  sum(specimen_count_max)  nb_physical_specimens_high FROM b  GROUP BY  gtu_country_tag_value, LOWER(type) ";
		
		$agg_table5=" ) SELECT  gtu_country_tag_value as countries ";
		$agg_table6=" , SUM(nb_database_records) AS nb_database_records, string_agg(spec_type||':'||(nb_database_records::varchar),'; ' ORDER BY spec_type) AS nb_records_by_type , SUM(nb_physical_specimens_low) AS nb_physical_specimens_low, string_agg(spec_type||':'||(nb_physical_specimens_low::varchar),'; '  ORDER BY spec_type) AS nb_specimen_min_by_type, SUM(nb_physical_specimens_high) AS nb_physical_specimens_high, string_agg(spec_type||':'||(nb_physical_specimens_high::varchar),'; '  ORDER BY spec_type) AS nb_specimen_max_by_type FROM c ";
		$agg_table7=" GROUP BY  gtu_country_tag_value";
		$agg_table8=" ORDER BY  gtu_country_tag_value ";
		
		
		if(strlen($year)>0 || strlen($creation_date_min)>0 || strlen($creation_date_max)>0)
		{
			$fields_agg[]="substring(fct_mask_date(from_date,  from_date_mask),1,4) as year";
			$group_agg[]="substring(fct_mask_date(from_date,  from_date_mask),1,4)";
			//$fields_agg[]="fct_mask_date(from_date,  from_date_mask) as year";
			//$group_agg[]="fct_mask_date(from_date,  from_date_mask) ";
			$fields[]="year";			
			$groups[]="year";
			if(strlen($creation_date_min)>0)
			{
				$tmp=explode("-",$creation_date_min);
				
					if(count($tmp)==3)
					{
						$tmp[1]=str_pad($tmp[1], 2, "0", STR_PAD_LEFT); 
						$tmp[2]=str_pad($tmp[2], 2, "0", STR_PAD_LEFT); 
						$creation_date_min=implode("-",$tmp);
						$where_agg[]="specimen_creation_date >= '".$creation_date_min."' ";
					}
				
				/*if(is_numeric(str_replace("-","",$creation_date_min)))
				{
					$where_agg[]="fct_mask_date(gtu_from_date,  gtu_from_date_mask) >= '".$creation_date_min."' ";
				}*/
			}
			if(strlen($creation_date_max)>0)
			{
				/*if(is_numeric(str_replace("-","",$creation_date_max)))
				{
					$where_agg[]="NULLIF(fct_mask_date(gtu_from_date,  gtu_from_date_mask),'xxxx-xx-xx') >= '".$creation_date_max."' ";
				}*/
				$tmp=explode("-",$creation_date_max);
				
					if(count($tmp)==3)
					{
						$tmp[1]=str_pad($tmp[1], 2, "0", STR_PAD_LEFT); 
						$tmp[2]=str_pad($tmp[2], 2, "0", STR_PAD_LEFT); 
						$creation_date_max=implode("-",$tmp);
						$where_agg[]="specimen_creation_date <= '".$creation_date_max."' ";
					}
				
			}
		}
		
		if(strlen($collecting_date_min)>0)
			{
				//$orders[]="collecting_year";
				//$fields[7]="collecting_year";
				
				//$params[":collecting_date_min"]=$collecting_date_min;
				$where_agg[]= "(from_date >= :collecting_date_min::timestamp AND from_date_mask !=0) ";
				//$groups[]="collecting_year";
			}
			
			if(strlen($collecting_date_max)>0)
			{
				
				//$orders[]="collecting_year";
				//$fields[8]="collecting_year";
				
				//$params[":collecting_date_max"]=$collecting_date_max;
				$where_agg[]= "(from_date <= :collecting_date_max::timestamp AND from_date_mask !=0 ) ";
				//$groups[]="collecting_year";
			}
			
			
		if(strlen($ig_num)>0)
		{
		
			
			$fields_agg[]="ig_num";
			$group_agg[]="ig_num";
			$where_agg[]= "ig_num = :=ig_num" ;
			$params[":ig_num"]=$ig_num;
			$fields[]="ig_num";			
			$groups[]="ig_num";
			
		}
		
		if($detailSubCollections)
		{
			
			$fields_agg[]="name_full_path";	
			
			$group_agg[]="name_full_path";	
			$groups[]	="name_full_path";			
			
			$fields[]="name_full_path";
			
			$fields_agg[]="grscicoll_code";
			$group_agg[]="grscicoll_code";
			$fields[]="grscicoll_code";
			$groups[]="grscicoll_code";

		}
		
		if($collectionID=="/")
		{
			$where_agg[]= "collection_full_path LIKE  :id||'%'";    
			$params[":id"]=$collectionID;				
		}
		elseif(strpos($collectionID, ","))
		{
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "collection_full_path LIKE '%/$tmp_id/%'";
				}
			}
			$where_agg[]="(".implode(" OR ", $whereTmp).")";
		}
		else
		{
			 $where_agg[]= "collection_full_path LIKE '%/'||:idb||'/%'";
			 $params[":idb"]=$collectionID;				
		}
	
		$fields_agg_str="";
		if(count($fields_agg)>0)
		{
			$fields_agg_str=",".implode(",", $fields_agg);
		}
		
		$group_agg_str="";
		if(count($group_agg)>0)
		{
			$group_agg_str=",".implode(",", $group_agg);
		}
		
		$where_agg_str="";
		if(count($where_agg)>0)
		{
			$where_agg_str=" WHERE ".implode(" AND ", $where_agg);
		}
		
		$fields_str="";
		if(count($fields))
		{
			$fields_str=",".implode(",",$fields );
		}
		
		$group_str="";
		if(count($groups)>0)
		{
			$groups_str=",".implode(",", $groups);
		}
		
		$query=$agg_table1.$fields_agg_str.$agg_table2.$where_agg_str.$agg_table3.$fields_agg_str.$agg_table4.$group_agg_str.$agg_table5.$fields_str.$agg_table6.$agg_table7.$groups_str.$agg_table8;
		
		
		
		$conn = Doctrine_Manager::connection();
		
		$q = $conn->prepare($query);
		
		foreach($params as $p=>$v)
		{				
			
				$q->bindParam($p, $v, PDO::PARAM_STR);
			
		}
		
		if(strlen($collecting_date_min)>0)
		{
			 $q->bindParam(":collecting_date_min", $collecting_date_min, PDO::PARAM_STR);
		}
		
		if(strlen($collecting_date_max)>0)
		{
			$q->bindParam(":collecting_date_max", $collecting_date_max, PDO::PARAM_STR);
		}
		
		
		 $q->execute();
		$items=$q->fetchAll(PDO::FETCH_ASSOC);
		
		return $items;
  
  }
  
  public function countTaxaInSpecimen($collectionID ="/", $year="", $creation_date_min="", $creation_date_max="",$collecting_date_min="", $collecting_date_max="", $ig_num="", $includeSubcollection=false, $detailSubCollections=false  ,$parent_only=false, $hide_private=false, $all=false)
  {
	  
	if($all)
	{
		$view_name="v_reporting_taxa_in_specimen_per_rank_collection_ref_year_igall";
	}
	else
	{
		$view_name="v_reporting_taxa_in_specimen_per_rank_collection_ref_year_ig";
	}
    //$view_name="v_reporting_taxa_in_specimen_per_rank_collection_ref_year_ig";
    $fields =Array();
    $groups =Array();
    $where =Array();
    $orders=Array();
    if($detailSubCollection==true)
    {
        $fields[0]="collection_name";
        $fields[1]="level_name";
        $groups[]="collection_name";
        $groups[]="level_name";
        
    }
   
    if(strlen($year)>0)
    {
        $fields[2]="year";
        $where[]= "year = :year";
        $groups[]="year";
    }
    
    if(strlen($creation_date_min)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(creation_date,'1706-01-01 00:00:00') >= date_trunc('day',:creation_date_min::timestamp with time zone)";
        $groups[]="year";
		$orders[]="year";
    }
    
    if(strlen($creation_date_max)>0)
    {
        $fields[2]="year";
        $where[]= "COALESCE(creation_date,'1706-01-01 00:00:00') <= (date_trunc('day',:creation_date_max::timestamp with time zone)  + (24*60*60 - 1) * interval '1 second')";
        $groups[]="year";
		$orders[]="year";
    }
    
     if(strlen($ig_num)>0)
    {
        $fields[3]="ig_num";
         $groups[]="ig_num";
        $where[]= "ig_num = :ig_num";
    }
    
    
    $fields[4]="COUNT(DISTINCT taxonomy_id) as nb_database_records";
   // $fields[5]="SUM(specimen_count_min) as nb_physical_specimens_low";
   // $fields[6]="SUM(specimen_count_max) as nb_physical_specimens_high";
    
	
	if(strlen($collecting_date_min)>0)
    {
		//$orders[]="collecting_year";
        //$fields[7]="collecting_year";
        $where[]= "gtu_from_date >= :collecting_date_min::timestamp";
        //$groups[]="collecting_year";
    }
	
	if(strlen($collecting_date_max)>0)
    {
		//$orders[]="collecting_year";
        //$fields[8]="collecting_year";
        $where[]= "gtu_from_date <= :collecting_date_max::timestamp";
        //$groups[]="collecting_year";
    }
	
	
    $orders[]="level_ref DESC";
    $groups[]="level_ref";
    $fields[1]="level_name";
    $groups[]="level_name";
    
    if($detailSubCollections)
    {
        
        $orders[]="collection_name";
        $fields[0]="collection_name";
        
        $groups[]="collection_name";
        $includeSubcollection=true;
    }
    
    if($includeSubcollection||$collectionID=="/")
    {
        
        if($collectionID=="/")
        {
            $where[]= "collection_path LIKE  :id||'%'";            
        }
		elseif(strpos($collectionID, ","))
		{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "collection_path||'/'||$view_name.collection_ref||'/' LIKE '%/$tmp_id/%'";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
		}
        else
        {
            //$where[]= "collections.id::varchar  = :ida";
            $where[]= "collection_path||'/'||$view_name.collection_ref||'/' LIKE '%/'||:idb||'/%'";
        }       
    }
	elseif(strpos($collectionID, ","))
	{
			
			$array_col_id=explode(",",$collectionID );
			$whereTmp=Array();
			foreach($array_col_id as $tmp_id)
			{
				if(is_numeric($tmp_id))
				{
					$whereTmp[]= "$view_name.collection_ref = $tmp_id";
				}
			}
			$where[]="(".implode(" OR ", $whereTmp).")";
	}
    else
    {
         $where[]= "$view_name.collection_ref::varchar  = :id";
    }
    
    
    
    ksort($fields);
	if($detailSubCollections)
	{
		$fields[]="grscicoll_code";
		$groups[]="grscicoll_code";
	}
   
   
   $hide_str="";
   if($hide_private)
   {
	   $hide_str=" INNER JOIN v_collections_full_path_recursive_grscicoll ON $view_name.collection_ref=v_collections_full_path_recursive_grscicoll.id AND is_public=true ";
   }
   else
   {
      $hide_str=" INNER JOIN v_collections_full_path_recursive_grscicoll ON $view_name.collection_ref=v_collections_full_path_recursive_grscicoll.id ";
   }
   
    if(strpos($collectionID, ",")&& $detailSubCollections)
	{
			
			$array_col_id=explode(",",$collectionID );
			$regex="path ||id::varchar||'/' as full_path, regexp_replace(path ||id::varchar||'/', '(\/(".implode("|", $array_col_id ).")/\d+\/).*', '\\1') as group_coll ";
			$fields[]=$regex;
			$groups[]="path";
			$groups[]="id";
			/*$fields[]="group_coll";
			$groups[]="full_path";
			$groups[]="group_coll";*/
    }
	elseif($collectionID=="/"&& $detailSubCollections)
	{
		$regex="path ||id::varchar||'/' as full_path,  regexp_replace(path ||id::varchar||'/', '(\/\d+/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="path";
		$groups[]="id";
		/*$fields[]="group_coll";
		$groups[]="full_path";
		$groups[]="group_coll";*/
	}
	elseif($detailSubCollections)
	{
		$regex="path ||id::varchar||'/' as full_path, regexp_replace(path ||id::varchar||'/', '(\/".$collectionID."/\d+\/).*', '\\1') as group_coll ";
		$fields[]=$regex;
		$groups[]="path";
		$groups[]="id";
		/*$fields[]="group_coll";
		$groups[]="full_path";
		$groups[]="group_coll";*/
	}
   
    $all_fields=implode(", ", $fields);
	
    //$sql ="SELECT ".$all_fields." FROM $view_name ".$hide_str." WHERE ".implode(" AND ", $where);
    
    /*if(count($groups)>0)
    {
        $sql = $sql." GROUP BY ".implode(", ", $groups);
    }
    
     if(count($orders)>0)
    {
        $sql = $sql." ORDER BY ".implode(", ", $orders);
    }*/
	
	if( $parent_only && $detailSubCollections)
	{
		$tmpsql ="SELECT ".$all_fields." FROM $view_name ".$hide_str." WHERE ".implode(" AND ", $where);
		if(count($groups)>0)
		{
			$tmpsql = $tmpsql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$tmpsql = $tmpsql." ORDER BY ".implode(", ", $orders);
		}
		$sql="with a as (".$tmpsql.") select 
REPLACE(name_full_path,'|','/')	  collection_path_text,
a.grscicoll_code,
level_name, 
sum(nb_database_records) nb_database_records
from a 
left join v_collections_full_path_recursive_grscicoll b
on b.path||b.id::varchar||'/' = group_coll
group by group_coll, name_full_path, a.grscicoll_code, level_name ORDER BY name_full_path;";
	}
	else
	{
		
		$sql ="SELECT ".$all_fields." FROM $view_name ".$hide_str." WHERE ".implode(" AND ", $where);
		
		if(count($groups)>0)
		{
			$sql = $sql." GROUP BY ".implode(", ", $groups);
		}
		
		 if(count($orders)>0)
		{
			$sql = $sql." ORDER BY ".implode(", ", $orders);
		}
	}
 
 
    $conn = Doctrine_Manager::connection();
    $q = $conn->prepare($sql);
    
     if(strlen($year)>0)
    {
        $q->bindParam(":year", $year);
    }
    
     if(strlen($ig_num)>0)
    {
       $q->bindParam(":ig_num", $ig_num, PDO::PARAM_STR);
    }
    
    if($includeSubcollection||$collectionID=="/")    
    {
        
        if($collectionID=="/")
        {
            $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
            
        }
        elseif(strpos($collectionID,",")===FALSE)
        {
            //$q->bindParam(":ida", $collectionID, PDO::PARAM_STR);
            $q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
        }       
    }
    elseif(strpos($collectionID,",")===FALSE)
    {
         $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_min)>0)
    {
         $q->bindParam(":creation_date_min", $creation_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($creation_date_max)>0)
    {
        $q->bindParam(":creation_date_max", $creation_date_max, PDO::PARAM_STR);
    }
       
    if(strlen($collecting_date_min)>0)
    {
         $q->bindParam(":collecting_date_min", $collecting_date_min, PDO::PARAM_STR);
    }
    
    if(strlen($collecting_date_max)>0)
    {
        $q->bindParam(":collecting_date_max", $collecting_date_max, PDO::PARAM_STR);
    }
   
    $q->execute();
    
    $items=$q->fetchAll(PDO::FETCH_ASSOC);

    return $items;
  }
  
  //ftheeten 2018 07 02
   public function getSpatialCoverage($collectionID, $includeSubcollection=false)
   {
	   
	   $sql = "SELECT 
		string_agg(DISTINCT gtu_country_tag_value, ',' ORDER BY gtu_country_tag_value) as countries, 
        min(gtu_location[0])::varchar||','||min(gtu_location[1])||','||max(gtu_location[0])::varchar||','||max(gtu_location[1]) as bbox
       FROM specimens";

	   
	   if($includeSubcollection||$collectionID=="/")
		{
        
			if($collectionID=="/")
			{
				$where[]= "collection_path LIKE  :id||'%'";            
			}
			else
			{
				$where[]= "collection_path||'/'||collection_ref||'/' LIKE '%/'||:idb||'/%'";
			}       
		}
		else
		{
			 $where[]= "collection_ref::varchar  = :id";
		}
		$sql= $sql." WHERE ".implode(" AND ", $where);
		$conn = Doctrine_Manager::connection();
		$q = $conn->prepare($sql);
		if($includeSubcollection||$collectionID=="/")    
		{
			
			if($collectionID=="/")
			{
				$q->bindParam(":id", $collectionID, PDO::PARAM_STR);
				
			}
			else
			{
				$q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
			}       
		}
		else
		{
			 $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
		}
	    $q->execute();
    
		$items=$q->fetchAll(PDO::FETCH_ASSOC);

		return $items;
   }
   
   
   //ftheeten 2018 07 02
   public function getTemporalCoverage($collectionID, $includeSubcollection=false)
   {
	   
	   $sql = "SELECT MIN(fct_mask_date(gtu_from_date, gtu_from_date_mask)) AS date_min, 
		MAX(
		CASE WHEN gtu_to_date_mask=0
		THEN
			fct_mask_date(
			gtu_from_date
			, 
			gtu_from_date_mask
			)
		ELSE
			fct_mask_date(
			gtu_to_date
			, 
			gtu_to_date_mask
			)
		END
		) 
		AS date_to
		 FROM specimens ";

	   
	   if($includeSubcollection||$collectionID=="/")
		{
        
			if($collectionID=="/")
			{
				$where[]= "collection_path LIKE  :id||'%'";            
			}
			else
			{
				$where[]= "collection_path||'/'||collection_ref||'/' LIKE '%/'||:idb||'/%'";
			}       
		}
		else
		{
			 $where[]= "collection_ref::varchar  = :id";
		}
		
		$where[]= "gtu_from_date_mask !=0";
		$sql= $sql." WHERE ".implode(" AND ", $where);
		$conn = Doctrine_Manager::connection();
		$q = $conn->prepare($sql);
		if($includeSubcollection||$collectionID=="/")    
		{
			
			if($collectionID=="/")
			{
				$q->bindParam(":id", $collectionID, PDO::PARAM_STR);
				
			}
			else
			{
				$q->bindParam(":idb", $collectionID, PDO::PARAM_STR);
			}       
		}
		else
		{
			 $q->bindParam(":id", $collectionID, PDO::PARAM_STR);
		}
	    $q->execute();
    
		$items=$q->fetchAll(PDO::FETCH_ASSOC);

		return $items;
   }
   
    //ftheeten 2017 07 05
    public static function getAllAvailableCollectionsHierarchical()
  {

    $q = Doctrine_Query::create()
      ->select('c.*')
      ->from('Collections c')  ;   
    $q->orderBy('name ASC');
    $res = $q->execute();
    $results = array(0 =>'All');
    $resultsTmp = array();
    $indexedResults = array();
    $mapping=array();
    $alphaPaths=array();
    foreach($res as $row)
    {
      $resultsTmp[$row->getId()] = $row->getName();
      $indexedResults[$row->getId()] = $row->getNameIndexed();
      $mapping[$row->getId()] = $row->getPath().'/'.$row->getId().'/';

    }
    foreach($mapping as $key=>$path)
    {
      $alphaPath=CollectionsTable::getAlphabeticalPath($path, $indexedResults);
      $alphaPaths[$alphaPath]=$key;
    }
    ksort($alphaPaths);
    foreach($alphaPaths as $alphaPath=>$colId)
    {
        $levels= substr_count( $alphaPath, "/");
        $results[$colId]= str_repeat("-", $levels-1).$resultsTmp[$colId];
    }
    return $results;
  }
  
  //ftheeten 2017 >08 01 ?
  public static function getAlphabeticalPath($path, $colNames)
  {

    $arrayPath=explode("/", $path);
    $returned="/";
    foreach($arrayPath as $item)
    {
        if(is_numeric($item))
        {            
            $collname=$colNames[$item];
             $returned.=$collname."/";
        }
    }
    return $returned;
  }
}
