<?php

/**
 * DoctrineDistinctTemporalInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctrineDistinctTemporalInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DoctrineDistinctTemporalInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DoctrineDistinctTemporalInformation');
    }
}