<?php

/**
 * DoctrineTemporalInformationGtuGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctrineTemporalInformationGtuGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DoctrineTemporalInformationGtuGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DoctrineTemporalInformationGtuGroup');
    }
}