<?php

/**
 * DoctrineTemporalInformationGtuGroupTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctrineTemporalInformationGtuGroupTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return DoctrineTemporalInformationGtuGroupTagsTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DoctrineTemporalInformationGtuGroupTags');
    }
	
public function getByMultipleIds(array $ids)
  {
    if( empty($ids))
      return $ids;

    $q = DQ::create()
      ->from('DoctrineTemporalInformationGtuGroupTags g')
      ->wherein('g.id', $ids)
      ->orderBy('g.id');

    
    return $q->execute();
  }
}