<?php

/**
 * DoctrineTemporalInformationGtuGroupUnnestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctrineTemporalInformationGtuGroupUnnestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return DoctrineTemporalInformationGtuGroupUnnestTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DoctrineTemporalInformationGtuGroupUnnest');
    }
}