<?php

/**
 * GeoreferencesByService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GeoreferencesByService extends BaseGeoreferencesByService
{
	public function getWkt()
	{
		$q = Doctrine_Query::create()
		  ->select('ST_ASTEXT(geom) as geom')
		  ->from('GeoreferencesByService g')
		  ->where('id = ?',$this->getId());		
		$tmp= $q->fetchOne();
		return $tmp["geom"];
	}
	
	public function getGeoJson()
	{
		$q = Doctrine_Query::create()
		  ->select('ST_ASGeoJSON(geom) as geom')
		  ->from('GeoreferencesByService g')
		  ->where('id = ?',$this->getId());		
		$tmp= $q->fetchOne();
		return $tmp["geom"];
	}
	
	
   public function getDescription($view = null)
  {
    $str = "<table>";
    
    $str .=  '<tr><th>Name</th><td class="name">'.$this->getName().'</td></tr>';
    $str .=  '<tr><th>Id</th><td class="id">'.$this->getId().'</td></tr>';
    $str .=  '<tr><th>Data Origin</th><td class="data_origin">'.$this->getDataOrigin().'</td></tr>';
	$str .=  '<tr><th>WFS URL</th><td class="wfs_url">'.$this->getWfsUrl().'</td></tr>';
	$str .=  '<tr><th>WFS Layer</th><td class="wfs_table">'.$this->getWfsTable().'</td></tr>';
	$str .=  '<tr><th>WFS ID</th><td class="wfs_id">'.$this->getWfsId().'</td></tr>';
    $str .= "</table>";
    return $str;
  }

	
}
