<?php

/**
 * GtuIso3166Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GtuIso3166Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return GtuIso3166Table The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GtuIso3166');
    }
	
	public function findISO3166Code($criteria)
	{
		$returned=[];
		$query= Doctrine_Query::create()->
		select("DISTINCT iso3166_code  , iso3166_name")->
		from('GtuIso3166 i')->
		where("LOWER(search_field) ~ LOWER(?)", $criteria)
		->andWhere("COALESCE(iso3166_2_code,'') ='' ")
		->orderBy("iso3166_name");
		$res=$query->execute();
		$unique=[];
		foreach($res as $row)
		{
		  if(!in_array($row->getIso3166Name(), $unique))
		  {
			  $unique[]=$row->getIso3166Name();
			  $data_row= [];
			  $data_row["iso3166_code"]=$row->getIso3166Code();
			  $data_row["iso3166_name"]=$row->getIso3166Name();
			  $returned[]=$data_row;
		  }
		  
        }
		return $returned;
	}
	
	public function findISO3166Level2Code($criteria)
	{
		
		
		$returned=[];
		$query= Doctrine_Query::create()->
		select("DISTINCT iso3166_2_code  , iso3166_2_name")->
		from('GtuIso3166 i')->
		where("LOWER(search_field) ~ LOWER(?)", $criteria)
			->andWhere("COALESCE(TRIM(iso3166_2_code,'')) !='' ")
		->orderBy("iso3166_2_name");
		$res=$query->execute();
		$unique=[];
		foreach($res as $row)
		{
		
		  if(!in_array($row->getIso3166_2Code(), $unique))
		  {
			  $unique[]=$row->getIso3166_2Code();
			  $data_row= [];
			  $data_row["iso3166_2_code"]=$row->getIso3166_2Code();
			  $data_row["iso3166_2_name"]=$row->getIso3166_2Name();
			  $returned[]=$data_row;
		  }
		  
        }
		return $returned;
	}
}