<?php

/**
 * GtuToGeorefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GtuToGeorefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return GtuToGeorefTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GtuToGeoref');
    }
	
	public function getGtuRelated($gtu_ref=null)
	  {
		 
		$q = Doctrine_Query::create()->
			 from('GtuToGeoref')->
			 where('gtu_ref = ?', $gtu_ref)->
			 orderBy('id');
		return $q->execute();
	  }
	  
	  public function getGtuByGeorefRelated($georef_ref=null)
	  {
		 
		$q = Doctrine_Query::create()->
			 from('GtuToGeoref')->
			 where('georef_ref = ?', $georef_ref)->
			 orderBy('id');
		return $q->execute();
	  }
	  
	  public function getGtuByGeorefFullyRelated($georef_ref=null, $gturef_ref=null)
	  {
		 
		$q = Doctrine_Query::create()->
			 from('GtuToGeoref')->
			 where('georef_ref = ?', $georef_ref)->
			 andWhere('gtu_ref = ?', $gturef_ref)->
			 orderBy('id');
		return $q->execute();
	  }
	  
	   public function deleteGtuByGeorefFullyRelated($georef_ref=null, $gturef_ref=null)
	  {
		 
		$q = Doctrine_Query::create()->
			 from('GtuToGeoref')->
			 where('georef_ref = ?', $georef_ref)->
			 andWhere('gtu_ref = ?', $gturef_ref)->
			 orderBy('id');
		$items= $q->execute();
		foreach($items as $item)
		{
			$item->delete();
		}
	  }
}