<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Lithology extends BaseLithology
{
  public function getNameWithFormat()
  {
    return $this->getName();
  }

  public function getName()
  {
    if(! $this->isNew() && $this->_get('id')==0)
      return '-';
    return $this->_get('name');
  }
  
    	//ftheeten 2017 08 07
    public function getTaxonomyMetadataName()
    {
        return Doctrine_Core::getTable('TaxonomyMetadata')->find($this->getMetadataRef())->getTaxonomyName();
    }
    
    public function getTaxonomyMetadataReferenceStatus()
    {
        return Doctrine_Core::getTable('TaxonomyMetadata')->find($this->getMetadataRef())->getIsReferenceTaxonomy();
    }
}
