<?php

/**
 * SpecimenIdentificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecimenIdentificationsTable extends IdentificationsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecimenIdentificationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpecimenIdentifications');
    }
}