<?php

/**
 * StagingGtuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StagingGtuTable extends DarwinTable
{

   
    public function getNonimportedData($import_ref)
    {
        $response = Doctrine_Query::create()
               ->select()
               ->from('StagingGtu')
               ->where('import_ref= ?', $import_ref)
               ->andWhere('imported= false')
				->orderBy('id')			   
               ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);

    return $response;     
    
    }
    
    public function getImportData($import_ref, $offset="0", $limit="1000")
    {
        $conn_MGR = Doctrine_Manager::connection();
		$conn = $conn_MGR->getDbh();
			
			
		$params[':import_ref'] = $import_ref;
		$params[':offset'] = $offset;
	    $params[':limit'] = $limit;
		$sql =" SELECT * FROM staging_gtu WHERE import_ref=:import_ref ORDER BY id OFFSET :offset LIMIT :limit;";
		$statement = $conn->prepare($sql);
		$statement->execute($params);
		$items = $statement->fetchAll(PDO::FETCH_ASSOC);
        return $items;
 
    
    }
    
    
    //2019 02 27
    public function countExceptionMessages($import_ref, $offset="0", $limit="1000")
	{
		$conn_MGR = Doctrine_Manager::connection();
		$conn = $conn_MGR->getDbh();
			
			
		$params[':import_ref'] = $import_ref;
		$params[':import_ref_2'] = $import_ref;
		$params[':offset'] = $offset;
	    $params[':limit'] = $limit;
		$sql =" SELECT count(*) as count, import_exception, (SELECT count(*) FROM staging_gtu WHERE import_ref=:import_ref_2   ) as count_all FROM (SELECT * FROM staging_gtu WHERE import_ref=:import_ref ORDER BY id  OFFSET :offset LIMIT :limit) a  GROUP BY import_exception ORDER BY import_exception  ;";
		$statement = $conn->prepare($sql);
		$statement->execute($params);
		$results = $statement->fetchAll(PDO::FETCH_ASSOC);
		return $results;
	}
}