<?php

/**
 * StorageParts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    darwin
 * @subpackage model
 * @author     DB team <darwin-ict@naturalsciences.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StorageParts extends BaseStorageParts
{
      public function setCategory($value)
      {
        if($value != $this->_get('category')) {
          $this->_set('category', $value);
        }
      }

      public static function getCategories()
      {
        return array(
          'physical' => 'Physical',
          'observation' => 'Observation',
          'figurate' => 'Figurate',
          'figurate-physical' => 'Figurate-Physical',
		  'dna_voucher'=> "DNA (voucher)",
		  'dna_tissue'=> "DNA (tissue)",
        );
      }
}
