<?php

/**
 * UsersTrackingSpecimensTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersTrackingSpecimensTable extends UsersTrackingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersTrackingSpecimensTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersTrackingSpecimens');
    }
}