<?php

/**
 * VCollectionsFullPathRecursiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VCollectionsFullPathRecursiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return VCollectionsFullPathRecursiveTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VCollectionsFullPathRecursive');
    }
}