<?php

/**
 * VGeorefForInterfaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VGeorefForInterfaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return VGeorefForInterfaceTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VGeorefForInterface');
    }
}