<?php

/**
 * WidgetProfilesDefinitionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WidgetProfilesDefinitionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return WidgetProfilesDefinitionTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WidgetProfilesDefinition');
    }
}