<?php

/**
 * GeometryColumnsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeometryColumnsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeometryColumnsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeometryColumns');
    }
}