# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class: sfAggregateLogger
    param:
      level: notice
      loggers:
        sf_web_debug:
          class: sfWebDebugLogger
          param:
            level: notice
            condition:       %SF_WEB_DEBUG%
            xdebug_logging:  false
            web_debug_class: sfWebDebug
        sf_file_debug:
          class: sfFileLogger
          param:
            level: notice
            file: %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
  mailer:
    #sender: your_send_email@example.com
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           utf-8
      delivery_strategy: none 
      transport:
        class: Swift_SmtpTransport
        param:
          host: mail1.museum.africamuseum.be      
          port: 25      
          encryption:  ~
          username: ~ 
          password:  ~ 

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host:       bernie
          port:       25
          encryption: ~
          username:   ~
          password:   ~
#   mailer:
#     param:
#       delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  storage:
    class: sfSessionStorage
    param:
      session_name: darwin2

  user:
    class: myUser
    param:
      timeout: 3600
