<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/12/19 11:14:08
sfConfig::add(array(
  'mod_cataloguewidgetview_enabled' => true,
  'mod_cataloguewidgetview_view_class' => 'sfPHP',
));
