<?php
// auto-generated by sfCacheConfigHandler
// date: 2018/03/06 09:22:16
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

