<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/21 09:45:03
sfConfig::add(array(
  'mod_cataloguewidget_enabled' => true,
  'mod_cataloguewidget_view_class' => 'sfPHP',
));
