<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/12 17:29:15
sfConfig::add(array(
  'mod_cataloguewidget_enabled' => true,
  'mod_cataloguewidget_view_class' => 'sfPHP',
));
