<?php
// auto-generated by sfCacheConfigHandler
// date: 2018/03/05 13:58:56
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

