<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/09 17:29:46
sfConfig::add(array(
  'mod_informativeworkflow_enabled' => true,
  'mod_informativeworkflow_view_class' => 'sfPHP',
));
