<?php
// auto-generated by sfCacheConfigHandler
// date: 2018/02/15 11:01:19
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

