<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/13 12:04:28
sfConfig::add(array(
  'mod_specimensearchwidget_enabled' => true,
  'mod_specimensearchwidget_view_class' => 'sfPHP',
));
