<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/07 10:15:06
sfConfig::add(array(
  'mod_taxonomymetadata_enabled' => true,
  'mod_taxonomymetadata_view_class' => 'sfPHP',
));
