<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/09/25 11:11:00
sfConfig::add(array(
  'mod_cataloguewidgetview_enabled' => true,
  'mod_cataloguewidgetview_view_class' => 'sfPHP',
));
