<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/05 13:59:05
sfConfig::add(array(
  'mod_informativeworkflow_enabled' => true,
  'mod_informativeworkflow_view_class' => 'sfPHP',
));
