<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/11/29 10:06:49
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

