<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/09 08:45:29
sfConfig::add(array(
  'mod_expeditionsigs_enabled' => true,
  'mod_expeditionsigs_view_class' => 'sfPHP',
));
