<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/06 09:22:16
sfConfig::add(array(
  'mod_specimensearch_enabled' => true,
  'mod_specimensearch_view_class' => 'sfPHP',
));
