<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/11/23 19:04:43
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

