<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/09/25 11:11:00
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

