<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/12/05 09:23:44
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

