<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/12/19 11:12:15
$this->security = array (
  'logout' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'lostpwd' => 
  array (
    'is_secure' => false,
  ),
  'pwdrenewmail' => 
  array (
    'is_secure' => false,
  ),
  'renewpwd' => 
  array (
    'is_secure' => false,
  ),
  'lang' => 
  array (
    'is_secure' => false,
  ),
  'submit' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
