<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/09 11:12:10
sfConfig::add(array(
  'mod_specimenwidgetview_enabled' => true,
  'mod_specimenwidgetview_view_class' => 'sfPHP',
));
