<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/09/21 18:06:48
sfConfig::add(array(
  'mod_informativeworkflow_enabled' => true,
  'mod_informativeworkflow_view_class' => 'sfPHP',
));
