<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/12/19 11:12:32
sfConfig::add(array(
  'mod_specimensearch_enabled' => true,
  'mod_specimensearch_view_class' => 'sfPHP',
));
