all:
  ldap:
    ldap_enabled: true
    host: dc2012.rbins.be
    port: 389
    user: adreader2
    pass: adReader2!
    baseuser: cn=Users, dc=rbins, dc=be
    version: 3
    attr_displayname: displayName
    attr_mail: mail
    attr_id: samaccountname
