#dev:
#  doctrine:
#    class: sfDoctrineDatabase
#    param:
#      dsn: 'pgsql:host=tyro;dbname=darwin2'
#     username: d2viewer
#      password: r2d2ford2
#           
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=localhost;dbname=darwin2_rbins_test'
      username: darwin2
      password: darwin@123
